type Schema = Record<string, unknown>;
const string = (extra: Schema = {}): Schema => ({ type: "string", ...extra });
const nullableString = (extra: Schema = {}): Schema => ({ type: ["string", "null"], ...extra });
const integer = (extra: Schema = {}): Schema => ({ type: "integer", ...extra });
const nullableInteger = (extra: Schema = {}): Schema => ({ type: ["integer", "null"], ...extra });
const boolean = (): Schema => ({ type: "boolean" });
const timestamp = (): Schema => string({ format: "date-time" });
const nullableTimestamp = (): Schema => ({ type: ["string", "null"], format: "date-time" });
const id = (): Schema => string({ minLength: 1, maxLength: 80 });
const nullableId = (): Schema => ({ type: ["string", "null"], minLength: 1, maxLength: 80 });
const object = (required: string[], properties: Record<string, Schema>): Schema => ({ type: "object", additionalProperties: false, required, properties });
const array = (items: Schema): Schema => ({ type: "array", items });
export const schemaRef = (name: string): Schema => ({ $ref: `#/components/schemas/${name}` });
const page = (item: string): Schema => object(["data", "pagination"], { data: array(schemaRef(item)), pagination: schemaRef("Pagination") });

const customer = object(["id", "externalReference", "businessName", "contactName", "email", "status", "creationSource", "createdAt", "updatedAt"], {
  id: id(), externalReference: string({ maxLength: 120 }), businessName: string({ maxLength: 200 }), contactName: string({ maxLength: 200 }), email: string({ format: "email", maxLength: 320 }), phone: nullableString({ maxLength: 50 }), industry: nullableString({ maxLength: 120 }), websiteUrl: nullableString({ format: "uri", maxLength: 500 }), status: string({ enum: ["PROSPECT", "ACTIVE", "SUSPENDED", "CANCELLED", "ARCHIVED"] }), creationSource: string({ enum: ["SELF_REGISTRATION", "ADMIN", "INVITATION", "MIGRATION"] }), createdAt: timestamp(), updatedAt: timestamp(),
});
const subscription = object(["id", "customerId", "planId", "status", "billingInterval", "currency", "version", "createdAt", "updatedAt"], {
  id: id(), customerId: id(), customerName: string(), planId: id(), planCode: string(), planName: string(), status: string({ enum: ["PENDING", "TRIAL", "ACTIVE", "PAST_DUE", "SUSPENDED", "CANCEL_AT_PERIOD_END", "CANCELLED", "EXPIRED"] }), billingInterval: string({ enum: ["MONTHLY", "ANNUAL"] }), currency: string({ pattern: "^[A-Z]{3}$" }), startedAt: nullableTimestamp(), currentPeriodStart: nullableTimestamp(), currentPeriodEnd: nullableTimestamp(), gracePeriodEndsAt: nullableTimestamp(), serviceExtendedUntil: nullableTimestamp(), cancelAt: nullableTimestamp(), cancelledAt: nullableTimestamp(), trialEndsAt: nullableTimestamp(), version: integer({ minimum: 1 }), createdAt: timestamp(), updatedAt: timestamp(),
});
const invoice = object(["id", "customerId", "invoiceNumber", "status", "currency", "subtotalMinor", "taxMinor", "totalMinor", "amountDueMinor", "createdAt", "updatedAt"], {
  id: id(), customerId: id(), customerName: string(), subscriptionId: nullableId(), invoiceNumber: string(), status: string({ enum: ["DRAFT", "OPEN", "PAID", "VOID", "UNCOLLECTIBLE"] }), currency: string({ pattern: "^[A-Z]{3}$" }), subtotalMinor: integer({ minimum: 0 }), taxMinor: integer({ minimum: 0 }), totalMinor: integer({ minimum: 0 }), amountDueMinor: integer({ minimum: 0 }), issuedAt: nullableTimestamp(), dueAt: nullableTimestamp(), paidAt: nullableTimestamp(), createdAt: timestamp(), updatedAt: timestamp(),
});
const discount = object(["id", "code", "name", "discountType", "durationType", "startsAt", "active", "stackable", "createdAt", "updatedAt"], {
  id: id(), code: string(), name: string(), description: nullableString(), discountType: string({ enum: ["PERCENTAGE", "FIXED_AMOUNT"] }), percentOffBasisPoints: nullableInteger({ minimum: 1, maximum: 10000 }), amountOffMinor: nullableInteger({ minimum: 1 }), currency: nullableString({ pattern: "^[A-Z]{3}$" }), durationType: string({ enum: ["ONCE", "REPEATING", "FOREVER"] }), durationMonths: nullableInteger({ minimum: 1 }), startsAt: timestamp(), endsAt: nullableTimestamp(), maxRedemptions: nullableInteger({ minimum: 1 }), active: boolean(), stackable: boolean(), createdAt: timestamp(), updatedAt: timestamp(),
});
const promotionCode = object(["id", "discountId", "discountCode", "discountName", "code", "startsAt", "redemptionCount", "firstPurchaseOnly", "active", "createdAt", "updatedAt"], {
  id: id(), discountId: id(), discountCode: string(), discountName: string(), code: string(), customerId: nullableId(), planId: nullableId(), startsAt: timestamp(), expiresAt: nullableTimestamp(), maxRedemptions: nullableInteger({ minimum: 1 }), redemptionCount: integer({ minimum: 0 }), firstPurchaseOnly: boolean(), active: boolean(), createdAt: timestamp(), updatedAt: timestamp(),
});
const notification = object(["id", "code", "recipientType", "channel", "status", "scheduledFor", "attemptCount", "maxAttempts", "createdAt", "updatedAt"], {
  id: id(), code: string(), customerId: nullableId(), recipientType: string({ enum: ["CUSTOMER", "ADMIN", "SYSTEM"] }), channel: string({ enum: ["EMAIL", "SMS", "WHATSAPP", "IN_APP"] }), status: string({ enum: ["PENDING", "PROCESSING", "SENT", "FAILED", "CANCELLED"] }), scheduledFor: timestamp(), attemptCount: integer({ minimum: 0 }), maxAttempts: integer({ minimum: 1 }), nextAttemptAt: nullableTimestamp(), sentAt: nullableTimestamp(), cancelledAt: nullableTimestamp(), readAt: nullableTimestamp(), errorCategory: nullableString(), createdAt: timestamp(), updatedAt: timestamp(),
});
const auditEvent = object(["id", "actorType", "action", "entityType", "requestId", "createdAt"], {
  id: id(), actorType: string({ enum: ["ANONYMOUS", "CUSTOMER", "ADMIN", "SERVICE", "SYSTEM"] }), actorId: nullableId(), action: string(), entityType: string(), entityId: nullableId(), before: {}, after: {}, requestId: string({ format: "uuid" }), createdAt: timestamp(),
});

export const apiSchemas = {
  Error: object(["error"], { error: object(["code", "message", "requestId"], { code: string(), message: string(), requestId: string({ format: "uuid" }) }) }),
  Pagination: object(["nextCursor", "hasMore"], { nextCursor: nullableString(), hasMore: boolean() }),
  Customer: customer, CustomerPage: page("Customer"),
  Subscription: subscription, SubscriptionPage: page("Subscription"),
  Invoice: invoice, InvoicePage: page("Invoice"),
  Discount: discount, DiscountPage: page("Discount"),
  PromotionCode: promotionCode, PromotionCodePage: page("PromotionCode"),
  Notification: notification, NotificationPage: page("Notification"),
  AuditEvent: auditEvent, AuditEventPage: page("AuditEvent"),
  PlanPrice: object(["billingInterval", "amountMinor", "setupFeeMinor", "currency", "taxBehaviour"], { id: id(), planId: id(), planName: string(), billingInterval: string({ enum: ["MONTHLY", "ANNUAL"] }), amountMinor: integer({ minimum: 0 }), setupFeeMinor: integer({ minimum: 0 }), currency: string({ pattern: "^[A-Z]{3}$" }), taxBehaviour: string({ enum: ["EXCLUSIVE", "INCLUSIVE", "EXEMPT"] }), effectiveFrom: timestamp(), effectiveTo: nullableTimestamp(), active: boolean(), createdAt: timestamp(), updatedAt: timestamp() }),
  PlanFeature: object(["code", "name", "included"], { code: string(), name: string(), included: boolean(), limitValue: nullableInteger({ minimum: 0 }), limitUnit: nullableString() }),
  PublicPlan: object(["code", "name", "featured", "displayOrder", "taxDisclosure", "prices", "features"], { code: string(), name: string(), description: nullableString(), featured: boolean(), displayOrder: integer({ minimum: 0 }), taxDisclosure: string(), prices: array(schemaRef("PlanPrice")), features: array(schemaRef("PlanFeature")) }),
  Plan: object(["id", "code", "name", "active", "featured", "custom", "displayOrder", "createdAt"], { id: id(), code: string(), name: string(), description: nullableString(), active: boolean(), featured: boolean(), custom: boolean(), displayOrder: integer({ minimum: 0 }), createdAt: timestamp(), updatedAt: timestamp() }),
  Offering: object(["id", "code", "name", "category", "active", "displayOrder", "createdAt"], { id: id(), code: string(), name: string(), description: nullableString(), category: string(), active: boolean(), displayOrder: integer({ minimum: 0 }), createdAt: timestamp(), updatedAt: timestamp() }),
  Entitlement: object(["enabled", "limitValue", "limitUnit"], { enabled: boolean(), limitValue: nullableInteger({ minimum: 0 }), limitUnit: nullableString() }),
  EntitlementValidation: object(["customerId", "subscriptionId", "subscriptionStatus", "planId", "validUntil", "valid", "entitlements"], { customerId: id(), subscriptionId: nullableId(), subscriptionStatus: string(), planId: nullableId(), validUntil: nullableString(), valid: boolean(), entitlements: { type: "object", additionalProperties: schemaRef("Entitlement") } }),
  AgentCustomer: object(["id", "businessName", "contactName", "email", "phone", "websiteUrl", "industry", "timezone", "state"], { id: id(), businessName: string(), contactName: string(), email: string({ format: "email" }), phone: nullableString(), websiteUrl: nullableString(), industry: nullableString(), timezone: string(), state: nullableString() }),
  AgentBootstrap: object(["customer", "onboarding", "subscription", "entitlements", "agentLink"], { customer: schemaRef("AgentCustomer"), onboarding: object(["status", "updatedAt"], { status: string(), updatedAt: nullableTimestamp() }), subscription: object(["status", "valid", "validUntil", "planCode"], { status: string(), valid: boolean(), validUntil: nullableString(), planCode: nullableString() }), entitlements: { type: "object", additionalProperties: schemaRef("Entitlement") }, agentLink: object(["platform", "externalAgentId", "status", "lastSyncedAt"], { platform: nullableString(), externalAgentId: nullableString(), status: string(), lastSyncedAt: nullableTimestamp() }) }),
  AgentLink: object(["customerId", "platform", "externalAgentId", "status", "lastSyncedAt", "version"], { customerId: id(), platform: string(), externalAgentId: nullableString(), status: string({ enum: ["ACTIVE", "SUSPENDED", "ERROR"] }), lastSyncedAt: nullableTimestamp(), version: integer({ minimum: 1 }) }),
  AgentReconciliation: object(["action"], { action: string({ enum: ["NONE", "QUEUED", "SYNCHRONIZED"] }), reason: nullableString(), operation: nullableString(), jobId: nullableId(), status: nullableString() }),
  AgentProcessingResult: object(["processed"], { processed: boolean(), job: { type: ["object", "null"] } }),
  BillingOverview: object(["profile", "subscription", "pricing", "paymentState", "entitlementState", "invoices", "notes"], { profile: { type: ["object", "null"] }, subscription: { oneOf: [schemaRef("Subscription"), { type: "null" }] }, pricing: { type: ["object", "null"] }, paymentState: string(), entitlementState: string(), invoices: array(schemaRef("Invoice")), notes: array(object(["id", "customerId", "body", "createdAt"], { id: id(), customerId: id(), subscriptionId: nullableId(), invoiceId: nullableId(), body: string(), createdAt: timestamp() })) }),
  CustomerBillingOverview: object(["profile", "subscription", "pricing", "paymentState", "entitlementState", "invoices"], { profile: { type: ["object", "null"] }, subscription: { type: ["object", "null"] }, pricing: { type: ["object", "null"] }, paymentState: string(), entitlementState: string(), invoices: array({ type: "object", required: ["id", "invoiceNumber", "status", "paymentState", "currency", "totalMinor", "amountDueMinor"], properties: { id: id(), invoiceNumber: string(), status: string(), paymentState: string(), currency: string(), totalMinor: integer(), amountDueMinor: integer(), issuedAt: nullableTimestamp(), dueAt: nullableTimestamp(), paidAt: nullableTimestamp() } }) }),
  CustomerAccount: object(["customer", "profile", "onboarding", "integrations", "subscription", "entitlements", "invoices", "reminders", "agentLinks", "agentJobs", "notificationPreferences", "inAppNotifications", "billing"], { customer: { type: "object", required: ["id", "externalReference", "businessName", "contactName", "email", "status", "createdAt"], properties: { id: id(), externalReference: string(), businessName: string(), contactName: string(), email: string({ format: "email" }), phone: nullableString(), status: string(), subscriptionStatus: nullableString(), planName: nullableString(), industry: nullableString(), websiteUrl: nullableString(), createdAt: timestamp() } }, profile: { type: ["object", "null"] }, onboarding: { type: ["object", "null"] }, integrations: array({ type: "object" }), subscription: { type: ["object", "null"] }, entitlements: array({ type: "object" }), invoices: array({ type: "object" }), reminders: array({ type: "object" }), agentLinks: array({ type: "object" }), agentJobs: array({ type: "object" }), notificationPreferences: array({ type: "object" }), inAppNotifications: array({ type: "object" }), billing: schemaRef("CustomerBillingOverview") }),
  OperationResult: object(["updated"], { updated: boolean() }),
  ProvisioningJob: object(["id", "customerId", "agentLinkId", "operation", "status", "attemptCount", "requestedAt"], { id: id(), customerId: id(), agentLinkId: id(), operation: string(), status: string(), attemptCount: integer({ minimum: 0 }), requestedAt: timestamp() }),
  PromotionValidation: object(["eligible", "code", "discount"], { eligible: boolean(), code: string(), discount: object(["type", "percentOffBasisPoints", "amountOffMinor", "currency", "durationType", "durationMonths"], { type: string(), percentOffBasisPoints: nullableInteger(), amountOffMinor: nullableInteger(), currency: nullableString(), durationType: string(), durationMonths: nullableInteger() }) }),
  BillingProfile: object(["id", "customerId", "contactName", "contactEmail", "updatedAt"], { id: id(), customerId: id(), contactName: string(), contactEmail: string({ format: "email" }), contactPhone: nullableString(), updatedAt: timestamp() }),
  BillingNote: object(["id", "customerId", "subscriptionId", "invoiceId", "body", "createdAt"], { id: id(), customerId: id(), subscriptionId: nullableId(), invoiceId: nullableId(), body: string(), createdAt: timestamp() }),
  PriceOverride: object(["id", "customerId", "planId", "billingInterval", "amountMinor", "setupFeeMinor", "currency", "status", "effectiveFrom", "effectiveTo", "reason"], { id: id(), customerId: id(), planId: id(), billingInterval: string(), amountMinor: integer(), setupFeeMinor: integer(), currency: string(), status: string(), effectiveFrom: timestamp(), effectiveTo: nullableTimestamp(), reason: string() }),
  CustomerDiscount: object(["id", "customerId", "discountId", "subscriptionId", "source", "status", "effectiveFrom", "effectiveTo", "reason"], { id: id(), customerId: id(), discountId: id(), subscriptionId: nullableId(), source: string(), status: string(), effectiveFrom: timestamp(), effectiveTo: nullableTimestamp(), reason: string() }),
  ServiceCredential: object(["id", "name", "scopes", "status", "expiresAt", "rotatedFromId", "createdAt"], { id: id(), name: string(), scopes: array(string()), status: string(), expiresAt: timestamp(), rotatedFromId: nullableId(), createdAt: timestamp() }),
  ServiceCredentialIssue: object(["credential", "token"], { credential: schemaRef("ServiceCredential"), token: string({ description: "Returned once and never persisted in plaintext." }) }),

  PromotionValidationRequest: object(["code", "customerId", "planId"], { code: string({ maxLength: 80 }), customerId: id(), planId: id() }),
  NotificationPreferenceRequest: object(["code", "channel", "status"], { code: string({ maxLength: 100 }), channel: string({ enum: ["EMAIL", "SMS", "WHATSAPP", "IN_APP"] }), status: string({ enum: ["OPTED_IN", "OPTED_OUT"] }) }),
  CreateCustomerRequest: object(["externalReference", "businessName", "contactName", "email"], { externalReference: string({ maxLength: 120 }), businessName: string({ maxLength: 200 }), contactName: string({ maxLength: 200 }), email: string({ format: "email", maxLength: 320 }), phone: nullableString({ maxLength: 50 }), industry: nullableString({ maxLength: 120 }), websiteUrl: nullableString({ maxLength: 500 }), tradingName: nullableString(), abn: nullableString(), timezone: nullableString(), state: nullableString(), suburb: nullableString(), postcode: nullableString() }),
  CreatePlanRequest: object(["code", "name"], { code: string(), name: string(), description: nullableString(), active: boolean(), featured: boolean(), custom: boolean(), displayOrder: integer({ minimum: 0 }) }),
  CreateOfferingRequest: object(["code", "name", "category"], { code: string(), name: string(), description: nullableString(), category: string(), active: boolean(), displayOrder: integer({ minimum: 0 }) }),
  CreatePriceRequest: object(["planId", "billingInterval", "amountMinor", "setupFeeMinor", "currency", "taxBehaviour", "effectiveFrom"], { planId: id(), billingInterval: string({ enum: ["MONTHLY", "ANNUAL"] }), amountMinor: integer({ minimum: 0 }), setupFeeMinor: integer({ minimum: 0 }), currency: string({ pattern: "^[A-Z]{3}$" }), taxBehaviour: string({ enum: ["EXCLUSIVE", "INCLUSIVE", "EXEMPT"] }), effectiveFrom: timestamp(), effectiveTo: nullableTimestamp() }),
  CreateSubscriptionRequest: object(["customerId", "planId", "billingInterval"], { customerId: id(), planId: id(), billingInterval: string({ enum: ["MONTHLY", "ANNUAL"] }), initialStatus: string({ enum: ["PENDING", "TRIAL", "ACTIVE"] }), trialEndsAt: nullableTimestamp(), currentPeriodStart: nullableTimestamp(), currentPeriodEnd: nullableTimestamp() }),
  BillingProfileRequest: object(["contactName", "contactEmail"], { contactName: string({ maxLength: 200 }), contactEmail: string({ format: "email", maxLength: 254 }), contactPhone: nullableString({ maxLength: 50 }) }),
  BillingNoteRequest: object(["body"], { subscriptionId: nullableId(), invoiceId: nullableId(), body: string({ maxLength: 4000 }) }),
  PricingPreviewRequest: object(["planId", "billingInterval"], { planId: id(), billingInterval: string({ enum: ["MONTHLY", "ANNUAL"] }), effectiveAt: nullableTimestamp(), includeSetupFee: boolean() }),
  PriceOverrideRequest: object(["planId", "billingInterval", "amountMinor", "setupFeeMinor", "currency", "effectiveFrom", "reason"], { planId: id(), billingInterval: string({ enum: ["MONTHLY", "ANNUAL"] }), amountMinor: integer({ minimum: 0 }), setupFeeMinor: integer({ minimum: 0 }), currency: string({ pattern: "^[A-Z]{3}$" }), effectiveFrom: timestamp(), effectiveTo: nullableTimestamp(), reason: string({ maxLength: 500 }) }),
  ApplyDiscountRequest: object(["discountId", "effectiveFrom", "reason"], { discountId: id(), subscriptionId: nullableId(), effectiveFrom: timestamp(), reason: string({ maxLength: 500 }) }),
  CreateDiscountRequest: object(["code", "name", "discountType", "durationType", "startsAt"], { code: string(), name: string(), description: nullableString(), discountType: string({ enum: ["PERCENTAGE", "FIXED_AMOUNT"] }), percentOffBasisPoints: nullableInteger(), amountOffMinor: nullableInteger(), currency: nullableString(), durationType: string({ enum: ["ONCE", "REPEATING", "FOREVER"] }), durationMonths: nullableInteger(), startsAt: timestamp(), endsAt: nullableTimestamp(), maxRedemptions: nullableInteger(), active: boolean(), stackable: boolean() }),
  CreatePromotionCodeRequest: object(["discountId", "startsAt"], { discountId: id(), code: nullableString(), customerId: nullableId(), planId: nullableId(), startsAt: timestamp(), expiresAt: nullableTimestamp(), maxRedemptions: nullableInteger(), firstPurchaseOnly: boolean(), active: boolean() }),
  ServiceCredentialRequest: object(["name", "scopes", "expiresAt"], { name: string({ maxLength: 160 }), scopes: array(string()), expiresAt: timestamp() }),
  RotateCredentialRequest: object(["expiresAt"], { expiresAt: timestamp() }),
  SubscriptionPatchRequest: object(["status"], { status: string(), gracePeriodEndsAt: nullableTimestamp() }),
  SubscriptionOperationRequest: object(["operation"], { operation: string({ enum: ["MARK_PAST_DUE", "SUSPEND", "RESUME", "SCHEDULE_CANCELLATION", "CANCEL_IMMEDIATELY", "FINALIZE_CANCELLATION", "EXTEND_SERVICE"] }), gracePeriodEndsAt: nullableTimestamp(), serviceExtendedUntil: nullableTimestamp(), reason: nullableString({ maxLength: 500 }) }),
  ProvisioningRequest: object(["platform", "operation"], { platform: string({ maxLength: 80 }), operation: string({ maxLength: 20 }) }),
  AgentLinkRequest: object(["platform", "status"], { platform: string({ maxLength: 80 }), externalAgentId: nullableString({ maxLength: 255 }), status: string({ enum: ["ACTIVE", "SUSPENDED", "ERROR"] }) }),
  AgentReconciliationRequest: object(["platform"], { platform: string({ maxLength: 80 }) }),
} as const;
