import assert from "node:assert/strict";
import test from "node:test";
import { AgentIntegrationService } from "../modules/agent/application/agent-integration-service.ts";

const repository = { findCustomerProfile: async (id: string) => id === "missing" ? null : ({ id, businessName: "Example Plumbing", contactName: "Casey", email: "casey@example.invalid", phone: "0400000000", websiteUrl: "https://example.invalid", industry: "Plumbing", timezone: "Australia/Sydney", state: "NSW" }), findOnboardingState: async () => ({ status: "IN_PROGRESS", updatedAt: new Date("2026-08-24T00:00:00.000Z") }), findAgentLink: async () => ({ platform: "zuno_agent", externalAgentId: null, status: "PENDING", lastSyncedAt: null }), findPlanCode: async () => "growth_engine" };

test("agent bootstrap composes only purpose-specific customer, onboarding, subscription, entitlement and link fields", async () => { const service = new AgentIntegrationService(repository, { getEntitlements: async (customerId: string) => ({ customerId, subscriptionId: "subscription-1", subscriptionStatus: "ACTIVE", planId: "plan-1", validUntil: "2026-09-30T00:00:00.000Z", valid: true, entitlements: { ai_receptionist: { enabled: true, limitValue: 500, limitUnit: "conversations" } } }) }); const dto = await service.buildBootstrapProfile("customer-1"); assert.equal(dto.subscription.planCode, "growth_engine"); assert.equal(dto.onboarding.status, "IN_PROGRESS"); assert.equal(dto.customer.email, "casey@example.invalid"); assert.equal(dto.entitlements.ai_receptionist.enabled, true); const json = JSON.stringify(dto); for (const forbidden of ["note", "priceOverride", "discount", "audit", "secret", "credential"]) assert.equal(json.toLowerCase().includes(forbidden.toLowerCase()), false); });

test("suspended subscriptions revoke service capability without hiding customer data", async () => { const service = new AgentIntegrationService(repository, { getEntitlements: async (customerId: string) => ({ customerId, subscriptionId: "subscription-1", subscriptionStatus: "SUSPENDED", planId: "plan-1", validUntil: null, valid: false, entitlements: { ai_receptionist: { enabled: false, limitValue: null, limitUnit: null } } }) }); const dto = await service.buildBootstrapProfile("customer-1"); assert.equal(dto.customer.businessName, "Example Plumbing"); assert.equal(dto.subscription.valid, false); assert.equal(dto.entitlements.ai_receptionist.enabled, false); });

test("missing customers are reported through the application boundary", async () => { await assert.rejects(() => new AgentIntegrationService(repository, { getEntitlements: async () => null }).buildBootstrapProfile("missing"), { code: "CUSTOMER_NOT_FOUND" }); });
