import assert from "node:assert/strict";
import test from "node:test";
import { apiRoute, assertAllowedFields, assertQueryParameters, decodeCursor, encodeCursor, jsonObject, paginationFrom } from "../app/api/v1/api-http.ts";
import { adminRoutePermission } from "../app/api/v1/admin/admin-route-contract.ts";
import { openApiDocument } from "../app/api/v1/openapi-document.ts";
import { mapApplicationError } from "../modules/shared/presentation/api-primitives.ts";
import { AuthenticationRequiredError, AuthorizationDeniedError, DomainConflictError, DomainValidationError, RateLimitExceededError, UnsupportedMediaTypeError } from "../modules/shared/domain/errors.ts";

test("opaque cursors bind to controlled sort order and reject invalid client input", () => { const position = { createdAt: new Date("2026-08-24T00:00:00.000Z"), id: "customer-1", direction: "desc" as const }; const cursor = encodeCursor(position); assert.deepEqual(decodeCursor(cursor), position); assert.equal(paginationFrom(new URL(`https://example.invalid/api?cursor=${cursor}&sort=-createdAt`)).direction, "desc"); assert.throws(() => paginationFrom(new URL(`https://example.invalid/api?cursor=${cursor}&sort=createdAt`)), { code: "CURSOR_SORT_MISMATCH" }); assert.throws(() => paginationFrom(new URL("https://example.invalid/api?sort=name")), { code: "INVALID_SORT" }); assert.throws(() => decodeCursor("not-a-cursor"), { code: "INVALID_CURSOR" }); });

test("OpenAPI inventories every purpose-specific surface with explicit production schemas", () => { assert.equal(openApiDocument.openapi, "3.1.0"); const paths = Object.keys(openApiDocument.paths); for (const prefix of ["/public/", "/customer/", "/admin/", "/integrations/agent/"]) assert.equal(paths.some((path) => path.startsWith(prefix)), true); for (const path of ["/admin/customers", "/admin/subscriptions", "/admin/invoices", "/admin/discounts", "/admin/promotion-codes", "/admin/notifications", "/admin/audit-events"]) assert.ok(openApiDocument.paths[path as keyof typeof openApiDocument.paths]); assert.equal(paths.includes("/webhooks/billing/{provider}"), true); assert.deepEqual(Object.keys(openApiDocument.components.securitySchemes).sort(), ["ChatGPTSession", "ServiceBearer", "StripeSignature"]); assert.ok(Object.keys(openApiDocument.components.schemas).length > 40); const text = JSON.stringify(openApiDocument); for (const schema of ["CustomerPage", "InvoicePage", "NotificationPage", "Error", "ServiceCredentialIssue"]) assert.match(text, new RegExp(schema)); assert.match(openApiDocument.info.description, /breaking changes require a new major namespace/i); });

test("OpenAPI authorization families match the executable route families", () => { for (const [path, item] of Object.entries(openApiDocument.paths)) for (const operation of Object.values(item)) { if (!operation || typeof operation !== "object" || !("responses" in operation)) continue; const security = JSON.stringify((operation as { security?: unknown }).security ?? []); if (path.startsWith("/admin/") || path.startsWith("/customer/")) assert.match(security, /ChatGPTSession/, path); if (path.startsWith("/integrations/agent/")) assert.match(security, /ServiceBearer/, path); if (path.startsWith("/public/")) assert.equal(security, "[]", path); } });

test("admin route authorization matrix is exact and rejects route-shape confusion", () => { const matrix: Array<["GET" | "POST" | "PATCH" | "DELETE", string[], string]> = [["GET", ["customers"], "CUSTOMER_READ"], ["POST", ["customers"], "CUSTOMER_WRITE"], ["GET", ["customers", "id", "pricing"], "PRICE_READ"], ["GET", ["customers", "id", "billing"], "BILLING_READ"], ["GET", ["invoices"], "BILLING_READ"], ["GET", ["notifications"], "OPERATIONS_READ"], ["GET", ["audit-events"], "AUDIT_READ"], ["POST", ["subscriptions", "id", "operations"], "SUBSCRIPTION_WRITE"], ["DELETE", ["service-credentials", "id"], "ADMIN_USER_MANAGE"]]; for (const [method, segments, permission] of matrix) assert.equal(adminRoutePermission(method, segments), permission); for (const invalid of [["subscriptions", "unexpected"], ["plans", "unexpected"], ["customers", "id", "secret"], ["service-credentials", "id", "unexpected"]]) assert.equal(adminRoutePermission("POST", invalid), null); });

test("request validation rejects unknown fields, unknown query parameters and non-JSON bodies", async () => { assert.throws(() => assertAllowedFields({ known: true, secret: true }, ["known"]), { code: "UNKNOWN_REQUEST_FIELD" }); assert.throws(() => assertQueryParameters(new URL("https://example.invalid/api?unsafe=true"), ["limit"]), { code: "UNKNOWN_QUERY_PARAMETER" }); await assert.rejects(() => jsonObject(new Request("https://example.invalid/api", { method: "POST", body: "{}" })), { code: "UNSUPPORTED_MEDIA_TYPE" }); });

test("REST problem mapping includes request IDs and 429 responses", () => { assert.deepEqual(mapApplicationError(new RateLimitExceededError(), "request-1"), { status: 429, body: { error: { code: "RATE_LIMIT_EXCEEDED", message: "Too many requests.", requestId: "request-1" } } }); });

test("REST boundary maps validation, authentication, authorization, media, missing, conflict and internal failures without stack traces", async () => { const request = new Request("https://example.invalid/api/v1/test"); const cases: Array<[Error, number]> = [[new DomainValidationError("INVALID_INPUT", "Invalid input."), 400], [new AuthenticationRequiredError(), 401], [new AuthorizationDeniedError(), 403], [new UnsupportedMediaTypeError(), 415], [new DomainConflictError("THING_NOT_FOUND", "Missing."), 404], [new DomainConflictError("THING_CONFLICT", "Conflict."), 409], [new Error("database password secret"), 500]]; for (const [error, status] of cases) { const response = await apiRoute(request, async () => { throw error; }); assert.equal(response.status, status); const json = JSON.stringify(await response.json()); assert.match(json, /requestId/); if (status === 500) { assert.equal(json.includes("database password secret"), false); assert.equal(json.includes("stack"), false); } } });
