import assert from "node:assert/strict";
import test from "node:test";
import { CreateOnboardingCaseService, OnboardingLifecycleService } from "../modules/onboarding/application/onboarding-services.ts";
import { D1OnboardingRepository } from "../modules/onboarding/infrastructure/d1-onboarding-repository.ts";
import { CustomerIntegrationService } from "../modules/integration/application/customer-integration-services.ts";
import { D1CustomerIntegrationRepository } from "../modules/integration/infrastructure/d1-customer-integration-repository.ts";
import { PublishNotificationTemplateService, QueueNotificationService, NotificationPreferenceService, DispatchNotificationService } from "../modules/notification/application/notification-services.ts";
import { D1NotificationRepository } from "../modules/notification/infrastructure/d1-notification-repository.ts";
import { RequestAgentProvisioningService, RunAgentProvisioningService } from "../modules/agent/application/agent-provisioning-services.ts";
import { D1AgentProvisioningRepository } from "../modules/agent/infrastructure/d1-agent-provisioning-repository.ts";
import { BillingAttentionProjectionService, OperationalQueueService } from "../modules/operations/application/operational-queue-services.ts";
import { D1OperationalQueueRepository } from "../modules/operations/infrastructure/d1-operational-queue-repository.ts";
import { DomainConflictError, DomainValidationError } from "../modules/shared/domain/errors.ts";
import { NOOP_AUDIT, RecordingAudit } from "./support/audit.ts";
import { repositoryDatabase } from "./support/sqlite-d1.ts";

const CUSTOMER_ID = "00000000-0000-4000-8000-000000000001";
const ADMIN_ID = "00000000-0000-4000-8000-000000000002";
const NOW = new Date("2026-08-24T00:00:00.000Z");
function setup() { const context = repositoryDatabase(); context.client.database.exec(`insert into customers (id,external_reference,business_name,contact_name,email,status,creation_source,created_at,updated_at) values ('${CUSTOMER_ID}','customer-1','Example Plumbing','Casey','casey@example.invalid','ACTIVE','ADMIN',1,1)`); context.client.database.exec(`insert into admin_users (id,identity_provider,external_subject,email,display_name,status,bootstrap,created_at,updated_at) values ('${ADMIN_ID}','test','admin-1','admin@example.invalid','Admin','ACTIVE',0,1,1)`); let sequence = 100; return { ...context, ids: { next: () => `90000000-0000-4000-8000-${(++sequence).toString().padStart(12, "0")}` }, clock: { now: () => NOW } }; }

test("onboarding owns task dependencies and projects only actionable customer/internal work", async () => {
  const context = setup(); const repository = new D1OnboardingRepository(context.database);
  const created = await new CreateOnboardingCaseService(repository, context.ids, context.clock, NOOP_AUDIT).execute(CUSTOMER_ID, [
    { code: "business_profile", title: "Confirm business profile", ownerType: "CUSTOMER" },
    { code: "configure_agent", title: "Configure agent", ownerType: "INTERNAL", dependsOnCodes: ["business_profile"] },
  ]);
  assert.equal(created.onboardingCase.props.status, "NOT_STARTED");
  assert.equal(context.client.database.prepare("select count(*) count from operational_queue_items where status='OPEN'").get()?.count, 1);
  const lifecycle = new OnboardingLifecycleService(repository, context.ids, context.clock, NOOP_AUDIT);
  await assert.rejects(() => lifecycle.transitionTask(created.onboardingCase.props.id.value, created.tasks[1].props.id.value, "DONE"), (error: unknown) => error instanceof DomainConflictError && error.code === "ONBOARDING_DEPENDENCY_INCOMPLETE");
  await lifecycle.transitionTask(created.onboardingCase.props.id.value, created.tasks[0].props.id.value, "DONE");
  assert.equal(context.client.database.prepare("select count(*) count from operational_queue_items where status='OPEN'").get()?.count, 1);
  const outcome = await lifecycle.transitionTask(created.onboardingCase.props.id.value, created.tasks[1].props.id.value, "DONE");
  assert.equal(outcome.onboardingCase.props.status, "READY");
  assert.equal(context.client.database.prepare("select count(*) count from operational_queue_items where status='OPEN'").get()?.count, 0);
  assert.equal(context.client.database.prepare("select status from customers where id=?").get(CUSTOMER_ID)?.status, "ACTIVE");
  context.client.close();
});

test("integration health opens and resolves internal action without storing credential metadata", async () => { const context = setup(); const service = new CustomerIntegrationService(new D1CustomerIntegrationRepository(context.database), context.ids, context.clock, NOOP_AUDIT); await assert.rejects(() => service.register({ customerId: CUSTOMER_ID, integrationCode: "crm", category: "CRM", metadata: { apiToken: "secret" } }), (error: unknown) => error instanceof DomainValidationError && error.code === "SENSITIVE_INTEGRATION_METADATA"); const integration = await service.register({ customerId: CUSTOMER_ID, integrationCode: "crm", category: "CRM", metadata: { tenant: "acme" } }); await service.updateHealth(integration.props.id.value, "ERROR", "AUTH_REVOKED"); assert.equal(context.client.database.prepare("select queue_type from operational_queue_items where status='OPEN'").get()?.queue_type, "INTERNAL_ACTION"); await service.updateHealth(integration.props.id.value, "HEALTHY"); assert.equal(context.client.database.prepare("select status from operational_queue_items").get()?.status, "COMPLETED"); context.client.close(); });

test("notification preferences are honoured except for required service notices and delivery is idempotent", async () => { const context = setup(); const repository = new D1NotificationRepository(context.database); const audit = new RecordingAudit(); const publish = new PublishNotificationTemplateService(repository, context.ids, context.clock, audit); await publish.execute({ code: "product_news", channel: "EMAIL", version: 1, subjectTemplate: "Hello {{name}}", bodyTemplate: "News for {{name}}" }); await new NotificationPreferenceService(repository, context.ids, context.clock, audit).set({ customerId: CUSTOMER_ID, code: "product_news", channel: "EMAIL", status: "OPTED_OUT", updatedBy: CUSTOMER_ID }); const queue = new QueueNotificationService(repository, context.ids, context.clock, audit); assert.equal(await queue.request({ code: "product_news", channel: "EMAIL", customerId: CUSTOMER_ID, recipientType: "CUSTOMER", recipientId: "casey@example.invalid", variables: { name: "Casey" }, idempotencyKey: "news-1" }), null); await publish.execute({ code: "payment_overdue", channel: "EMAIL", version: 1, subjectTemplate: "Payment due", bodyTemplate: "Invoice {{invoice}} is overdue", requiredServiceNotice: true }); const delivery = await queue.request({ code: "payment_overdue", channel: "EMAIL", customerId: CUSTOMER_ID, recipientType: "CUSTOMER", recipientId: "casey@example.invalid", variables: { invoice: "ZP-1" }, idempotencyKey: "invoice-ZP-1-overdue" }); assert.ok(delivery); assert.equal((await queue.request({ code: "payment_overdue", channel: "EMAIL", customerId: CUSTOMER_ID, recipientType: "CUSTOMER", recipientId: "casey@example.invalid", variables: { invoice: "ZP-1" }, idempotencyKey: "invoice-ZP-1-overdue" }))?.props.id.value, delivery.props.id.value); let rendered = ""; const sent = await new DispatchNotificationService(repository, { send: async (input) => { rendered = `${input.subject}|${input.body}`; return { providerReference: "provider-1" }; } }, context.clock, audit).execute(); assert.equal(sent?.props.status, "SENT"); assert.equal(rendered, "Payment due|Invoice ZP-1 is overdue"); assert.equal(audit.records.some((event) => event.action === "NOTIFICATION_SENT"), true); context.client.close(); });

test("notification provider failures schedule a durable retry", async () => { const context = setup(); const repository = new D1NotificationRepository(context.database); const publish = new PublishNotificationTemplateService(repository, context.ids, context.clock, NOOP_AUDIT); await publish.execute({ code: "onboarding_action", channel: "IN_APP", version: 1, bodyTemplate: "Complete {{task}}" }); await new QueueNotificationService(repository, context.ids, context.clock, NOOP_AUDIT).request({ code: "onboarding_action", channel: "IN_APP", customerId: CUSTOMER_ID, recipientType: "CUSTOMER", recipientId: CUSTOMER_ID, variables: { task: "profile" }, idempotencyKey: "onboarding-action-1" }); await assert.rejects(() => new DispatchNotificationService(repository, { send: async () => { throw new Error("temporary provider outage"); } }, context.clock, NOOP_AUDIT).execute(), /temporary provider outage/); const row = context.client.database.prepare("select status,attempt_count,next_attempt_at from notification_deliveries").get(); assert.equal(row?.status, "PENDING"); assert.equal(row?.attempt_count, 1); assert.equal(Number(row?.next_attempt_at) > NOW.getTime(), true); context.client.close(); });

test("agent provisioning is idempotent, provider-neutral, queued, and auditable", async () => { const context = setup(); const repository = new D1AgentProvisioningRepository(context.database); const audit = new RecordingAudit(); const request = new RequestAgentProvisioningService(repository, context.ids, context.clock, audit); const job = await request.execute({ customerId: CUSTOMER_ID, platform: "zuno_agent", operation: "PROVISION", idempotencyKey: "provision-customer-1" }); const duplicate = await request.execute({ customerId: CUSTOMER_ID, platform: "zuno_agent", operation: "PROVISION", idempotencyKey: "provision-customer-1" }); assert.equal(duplicate.props.id.value, job.props.id.value); const completed = await new RunAgentProvisioningService(repository, { execute: async () => ({ externalAgentId: "external-agent-1" }) }, context.clock, audit).execute(); assert.equal(completed?.props.status, "SUCCEEDED"); assert.equal(context.client.database.prepare("select status from agent_links").get()?.status, "ACTIVE"); assert.equal(context.client.database.prepare("select status from operational_queue_items where queue_type='AGENT_PROVISIONING'").get()?.status, "COMPLETED"); context.client.close(); });

test("agent provider failures preserve the queue and schedule a bounded retry", async () => { const context = setup(); const repository = new D1AgentProvisioningRepository(context.database); await new RequestAgentProvisioningService(repository, context.ids, context.clock, NOOP_AUDIT).execute({ customerId: CUSTOMER_ID, platform: "zuno_agent", operation: "PROVISION", idempotencyKey: "provision-retry-1" }); await assert.rejects(() => new RunAgentProvisioningService(repository, { execute: async () => { throw new Error("agent provider unavailable"); } }, context.clock, NOOP_AUDIT).execute(), /agent provider unavailable/); const job = context.client.database.prepare("select status,attempt_count,next_attempt_at from agent_provisioning_jobs").get(); assert.equal(job?.status, "PENDING"); assert.equal(job?.attempt_count, 1); assert.equal(Number(job?.next_attempt_at) > NOW.getTime(), true); assert.equal(context.client.database.prepare("select status from operational_queue_items where queue_type='AGENT_PROVISIONING'").get()?.status, "OPEN"); context.client.close(); });

test("billing attention is a reconciled projection and queue resolution does not mutate billing source state", async () => { const context = setup(); const repository = new D1OperationalQueueRepository(context.database); const service = new BillingAttentionProjectionService(repository, context.ids, context.clock, NOOP_AUDIT); const item = await service.project({ sourceType: "INVOICE", sourceId: "invoice-1", customerId: CUSTOMER_ID, title: "Invoice requires attention", requiresAttention: true }); assert.ok(item); const same = await service.project({ sourceType: "INVOICE", sourceId: "invoice-1", customerId: CUSTOMER_ID, title: "Invoice requires attention", requiresAttention: true }); assert.equal(same?.props.id.value, item.props.id.value); const queue = new OperationalQueueService(repository, context.clock, NOOP_AUDIT); await queue.claim(item.props.id.value, ADMIN_ID); await queue.resolve(item.props.id.value, "COMPLETED"); assert.equal(context.client.database.prepare("select status from operational_queue_items where id=?").get(item.props.id.value)?.status, "COMPLETED"); context.client.close(); });
