import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";

const NAMES = ["0000_uneven_violations.sql", "0001_last_rafael_vega.sql", "0002_windy_sprite.sql", "0003_strange_absorbing_man.sql", "0004_bored_red_ghost.sql", "0005_spotty_iron_fist.sql"];
function apply(database: DatabaseSync, name: string) { const url = new URL(`../drizzle/${name}`, import.meta.url); for (const statement of readFileSync(url, "utf8").split("--> statement-breakpoint")) if (statement.trim()) database.exec(statement); }
function upgraded() { const database = new DatabaseSync(":memory:"); database.exec("PRAGMA foreign_keys = ON"); for (const name of NAMES.slice(0, -1)) apply(database, name); database.exec("insert into customers (id,external_reference,business_name,contact_name,email,status,creation_source,created_at,updated_at) values ('00000000-0000-4000-8000-000000000001','customer-1','Example Plumbing','Casey','casey@example.invalid','ACTIVE','ADMIN',1,1)"); apply(database, NAMES.at(-1)!); return database; }

test("Phase 7 migration upgrades Phase 6 and creates operational infrastructure without changing customer lifecycle", () => { const database = upgraded(); const tables = database.prepare("select name from sqlite_schema where type = 'table' and name not like 'sqlite_%'").all().map((row) => String(row.name)); assert.equal(tables.length, 38); for (const name of ["onboarding_cases", "onboarding_tasks", "onboarding_task_dependencies", "customer_integrations", "agent_links", "agent_provisioning_jobs", "operational_queue_items", "notification_templates", "notification_preferences", "notification_deliveries"]) assert.equal(tables.includes(name), true); assert.equal(database.prepare("select status from customers").get()?.status, "ACTIVE"); database.close(); });

test("database enforces onboarding concurrency, dependency scope, and one current case", () => { const db = upgraded(); const customer = "00000000-0000-4000-8000-000000000001"; db.exec(`insert into onboarding_cases (id,customer_id,status,version,created_at,updated_at) values ('10000000-0000-4000-8000-000000000001','${customer}','NOT_STARTED',1,10,10)`); assert.throws(() => db.exec(`insert into onboarding_cases (id,customer_id,status,version,created_at,updated_at) values ('10000000-0000-4000-8000-000000000002','${customer}','NOT_STARTED',1,10,10)`), /onboarding_cases.customer_id/); assert.throws(() => db.exec("update onboarding_cases set status='IN_PROGRESS',started_at=11,version=1,updated_at=11 where id='10000000-0000-4000-8000-000000000001'"), /ONBOARDING_VERSION_CONFLICT/); db.close(); });

test("database protects queue, notification, integration, and agent optimistic versions", () => { const db = upgraded(); const customer = "00000000-0000-4000-8000-000000000001"; db.exec(`insert into operational_queue_items (id,queue_type,source_type,source_id,customer_id,status,priority,title,available_at,version,created_at,updated_at) values ('20000000-0000-4000-8000-000000000001','BILLING_ATTENTION','INVOICE','invoice-1','${customer}','OPEN',20,'Invoice overdue',10,1,10,10)`); assert.throws(() => db.exec("update operational_queue_items set status='COMPLETED',resolved_at=11,version=1,updated_at=11 where id='20000000-0000-4000-8000-000000000001'"), /QUEUE_VERSION_CONFLICT/); db.exec("insert into notification_templates (id,code,channel,version,subject_template,body_template,active,created_at,updated_at) values ('30000000-0000-4000-8000-000000000001','invoice_due','EMAIL',1,'Due','Body',1,10,10)"); assert.throws(() => db.exec("update notification_templates set body_template='Changed' where id='30000000-0000-4000-8000-000000000001'"), /NOTIFICATION_TEMPLATE_IMMUTABLE/); db.close(); });

test("operational indexes support ready work and notification retry queries", () => { const db = upgraded(); const plans = db.prepare("explain query plan select * from operational_queue_items where queue_type='INTERNAL_ACTION' and status='OPEN' order by priority,available_at").all().map((row) => String(row.detail)).join(" "); assert.match(plans, /operational_queue_items_work_idx/); const deliveryPlan = db.prepare("explain query plan select * from notification_deliveries where status='PENDING' and next_attempt_at <= 10").all().map((row) => String(row.detail)).join(" "); assert.match(deliveryPlan, /notification_deliveries_retry_idx/); db.close(); });
