import { and, asc, eq, lte } from "drizzle-orm";
import type { AppDatabase } from "../../../db/index.ts";
import { agentLinks, agentProvisioningJobs } from "../../../db/schema.ts";
import { DomainConflictError } from "../../shared/domain/errors.ts";
import { EntityId, StableCode } from "../../shared/domain/value-objects.ts";
import type { OperationalQueueItem } from "../../operations/domain/operational-queue.ts";
import { findActiveOperationalQueueRows, insertOperationalQueueItem, resolveOperationalQueueItem } from "../../operations/infrastructure/d1-operational-queue-statements.ts";
import type { AgentProvisioningRepository } from "../application/ports.ts";
import { AgentLink, AgentProvisioningJob, type AgentJobStatus, type AgentLinkStatus, type AgentOperation } from "../domain/agent-provisioning.ts";

export class D1AgentProvisioningRepository implements AgentProvisioningRepository {
  constructor(private readonly db: AppDatabase) {}
  async findLink(customerId: string, platform: string) { const [row] = await this.db.select().from(agentLinks).where(and(eq(agentLinks.customerId, customerId), eq(agentLinks.agentPlatform, platform))).limit(1); return row ? mapLink(row) : null; }
  async findLinkById(id: string) { const [row] = await this.db.select().from(agentLinks).where(eq(agentLinks.id, id)).limit(1); return row ? mapLink(row) : null; }
  async findJobByIdempotencyKey(key: string) { const [row] = await this.db.select().from(agentProvisioningJobs).where(eq(agentProvisioningJobs.idempotencyKey, key)).limit(1); return row ? mapJob(row) : null; }
  async findReadyJob(at: Date) { const [row] = await this.db.select().from(agentProvisioningJobs).where(and(eq(agentProvisioningJobs.status, "PENDING"), lte(agentProvisioningJobs.nextAttemptAt, at))).orderBy(asc(agentProvisioningJobs.nextAttemptAt), asc(agentProvisioningJobs.requestedAt)).limit(1); return row ? mapJob(row) : null; }
  async createRequest(link: AgentLink, expectedLinkVersion: number | null, job: AgentProvisioningJob, queue: OperationalQueueItem) { type BatchItem = Parameters<AppDatabase["batch"]>[0][number]; const lp = link.props; const statements: BatchItem[] = [expectedLinkVersion == null ? this.db.insert(agentLinks).values(linkValues(link)) : this.db.update(agentLinks).set({ status: lp.status, version: expectedLinkVersion + 1, updatedAt: lp.updatedAt }).where(eq(agentLinks.id, lp.id.value)), this.db.insert(agentProvisioningJobs).values(jobValues(job)), insertOperationalQueueItem(this.db, queue)]; try { await this.db.batch(statements as [BatchItem, ...BatchItem[]]); } catch (error) { throw mapConflict(error); } }
  async startJob(job: AgentProvisioningJob, expectedVersion: number) { const p = job.props; const result = await this.db.update(agentProvisioningJobs).set({ status: p.status, startedAt: p.startedAt, nextAttemptAt: p.nextAttemptAt, attemptCount: p.attemptCount, version: p.version, updatedAt: p.updatedAt }).where(and(eq(agentProvisioningJobs.id, p.id.value), eq(agentProvisioningJobs.version, expectedVersion))); if (Number(result.meta.changes) !== 1) throw new DomainConflictError("AGENT_JOB_VERSION_CONFLICT", "Agent job changed concurrently."); }
  async saveOutcome(link: AgentLink, expectedLinkVersion: number, job: AgentProvisioningJob, expectedJobVersion: number, resolveQueue: boolean) { const lp = link.props; const jp = job.props; const queues = resolveQueue ? await findActiveOperationalQueueRows(this.db, "AGENT_PROVISIONING_JOB", jp.id.value) : []; type BatchItem = Parameters<AppDatabase["batch"]>[0][number]; const statements: BatchItem[] = [this.db.update(agentLinks).set({ externalAgentId: lp.externalAgentId, status: lp.status, lastSyncedAt: lp.lastSyncedAt, version: expectedLinkVersion + 1, updatedAt: jp.updatedAt }).where(eq(agentLinks.id, lp.id.value)), this.db.update(agentProvisioningJobs).set({ status: jp.status, completedAt: jp.completedAt, errorCategory: jp.errorCategory, nextAttemptAt: jp.nextAttemptAt, version: expectedJobVersion + 1, updatedAt: jp.updatedAt }).where(eq(agentProvisioningJobs.id, jp.id.value)), ...queues.map((queue) => resolveOperationalQueueItem(this.db, queue, jp.updatedAt))]; try { await this.db.batch(statements as [BatchItem, ...BatchItem[]]); } catch (error) { throw mapConflict(error); } }
}
function linkValues(value: AgentLink) { const p = value.props; return { id: p.id.value, customerId: p.customerId.value, agentPlatform: p.agentPlatform.value, externalAgentId: p.externalAgentId, status: p.status, lastSyncedAt: p.lastSyncedAt, version: p.version, createdAt: p.createdAt, updatedAt: p.updatedAt }; }
function jobValues(value: AgentProvisioningJob) { const p = value.props; return { id: p.id.value, agentLinkId: p.agentLinkId.value, customerId: p.customerId.value, operation: p.operation, status: p.status, idempotencyKey: p.idempotencyKey, attemptCount: p.attemptCount, maxAttempts: p.maxAttempts, nextAttemptAt: p.nextAttemptAt, errorCategory: p.errorCategory, requestedAt: p.requestedAt, startedAt: p.startedAt, completedAt: p.completedAt, version: p.version, createdAt: p.createdAt, updatedAt: p.updatedAt }; }
function mapLink(row: typeof agentLinks.$inferSelect) { return new AgentLink({ id: new EntityId(row.id), customerId: new EntityId(row.customerId), agentPlatform: new StableCode(row.agentPlatform), externalAgentId: row.externalAgentId, status: row.status as AgentLinkStatus, lastSyncedAt: row.lastSyncedAt, version: row.version, createdAt: row.createdAt, updatedAt: row.updatedAt }); }
function mapJob(row: typeof agentProvisioningJobs.$inferSelect) { return new AgentProvisioningJob({ id: new EntityId(row.id), agentLinkId: new EntityId(row.agentLinkId), customerId: new EntityId(row.customerId), operation: row.operation as AgentOperation, status: row.status as AgentJobStatus, idempotencyKey: row.idempotencyKey, attemptCount: row.attemptCount, maxAttempts: row.maxAttempts, nextAttemptAt: row.nextAttemptAt, errorCategory: row.errorCategory, requestedAt: row.requestedAt, startedAt: row.startedAt, completedAt: row.completedAt, version: row.version, createdAt: row.createdAt, updatedAt: row.updatedAt }); }
function mapConflict(error: unknown): DomainConflictError { const message = error instanceof Error ? error.message : ""; if (message.includes("idempotency_key")) return new DomainConflictError("AGENT_JOB_IDEMPOTENCY_CONFLICT", "Agent job already exists."); if (message.includes("VERSION_CONFLICT")) return new DomainConflictError("AGENT_VERSION_CONFLICT", "Agent provisioning state changed concurrently."); throw error; }
