import { DomainConflictError } from "@/modules/shared/domain/errors";
import { CustomerBillingOverviewService } from "@/modules/billing/application/billing-operations-services";
import { D1BillingRepository } from "@/modules/billing/infrastructure/d1-billing-repository";
import { D1SubscriptionRepository } from "@/modules/subscription/infrastructure/d1-subscription-repository";
import { apiRoute, dataResponse } from "../../api-http";
import { authenticateCustomer, createApiRuntime } from "../../api-runtime";

export async function GET(request: Request) { return apiRoute(request, async ({ requestId }) => { const runtime = await createApiRuntime(request, requestId); const { principal } = await authenticateCustomer(runtime); const [account, billing] = await Promise.all([runtime.portal.getCustomerAccount(principal.customerId), new CustomerBillingOverviewService(new D1BillingRepository(runtime.db), new D1SubscriptionRepository(runtime.db), runtime.clock).execute(principal.customerId)]); if (!account) throw new DomainConflictError("CUSTOMER_NOT_FOUND", "Customer account does not exist."); return dataResponse({ ...account, billing: customerBillingDto(billing) }, 200, { "cache-control": "private, no-store" }); }); }

function customerBillingDto(value: Awaited<ReturnType<CustomerBillingOverviewService["execute"]>>) { return { profile: value.profile ? { contactName: value.profile.contactName, contactEmail: value.profile.contactEmail.value, contactPhone: value.profile.contactPhone } : null, subscription: value.subscription ? { status: value.subscription.status, currentPeriodStart: value.subscription.currentPeriodStart, currentPeriodEnd: value.subscription.currentPeriodEnd, gracePeriodEndsAt: value.subscription.gracePeriodEndsAt, serviceExtendedUntil: value.subscription.serviceExtendedUntil, cancelAt: value.subscription.cancelAt } : null, pricing: value.pricing, paymentState: value.paymentState, entitlementState: value.entitlementState, invoices: value.invoices.map((invoice) => ({ id: invoice.id.value, invoiceNumber: invoice.invoiceNumber, status: invoice.status, paymentState: invoice.paymentState, currency: invoice.currency, totalMinor: invoice.total.amountMinor, amountDueMinor: invoice.amountDue.amountMinor, issuedAt: invoice.issuedAt, dueAt: invoice.dueAt, paidAt: invoice.paidAt })) }; }
