import { and, desc, eq, gt, isNull, like, lt, lte, or } from "drizzle-orm";
import type { AnySQLiteColumn } from "drizzle-orm/sqlite-core";
import { PUBLIC_PRICE_TAX_DISCLOSURE } from "../../pricing/domain/tax-policy.ts";
import type { AppDatabase } from "../../../db/index.ts";
import { auditEvents, customers, discounts, offerings, planFeatures, planPrices, plans, promotionCodes, subscriptions } from "../../../db/schema.ts";
import type { ApiPage, ApiReadRepository, CursorPosition } from "../application/read-ports.ts";

export class D1ApiReadRepository implements ApiReadRepository {
  constructor(private readonly db: AppDatabase) {}

  async listPublicPlans(at: Date) {
    const rows = await this.db.select({ plan: plans, price: planPrices }).from(plans).leftJoin(planPrices, and(eq(planPrices.planId, plans.id), eq(planPrices.active, true), lte(planPrices.effectiveFrom, at), or(isNull(planPrices.effectiveTo), gt(planPrices.effectiveTo, at)))).where(and(eq(plans.active, true), eq(plans.custom, false))).orderBy(plans.displayOrder, plans.code, planPrices.billingInterval);
    const features = await this.db.select({ planId: planFeatures.planId, code: offerings.code, name: offerings.name, included: planFeatures.included, limitValue: planFeatures.limitValue, limitUnit: planFeatures.limitUnit }).from(planFeatures).innerJoin(offerings, eq(offerings.id, planFeatures.offeringId)).where(eq(offerings.active, true)).orderBy(offerings.displayOrder);
    const grouped = new Map<string, Record<string, unknown>>();
    for (const row of rows) { const current = grouped.get(row.plan.id) ?? publicPlan(row.plan); if (row.price) (current.prices as unknown[]).push({ billingInterval: row.price.billingInterval, amountMinor: row.price.amountMinor, setupFeeMinor: row.price.setupFeeMinor, currency: row.price.currency, taxBehaviour: row.price.taxBehaviour }); grouped.set(row.plan.id, current); }
    for (const feature of features) { const plan = grouped.get(feature.planId); if (plan) (plan.features as unknown[]).push({ code: feature.code, name: feature.name, included: feature.included, limitValue: feature.limitValue, limitUnit: feature.limitUnit }); }
    return [...grouped.values()];
  }
  async getPublicPlan(code: string, at: Date) { return (await this.listPublicPlans(at)).find((plan) => plan.code === code.trim().toLowerCase()) ?? null; }

  async listCustomers(input: { cursor: CursorPosition | null; limit: number; status?: string; query?: string }) {
    const query = input.query?.trim().slice(0, 120); const pattern = query ? `%${query.replaceAll("%", "\\%").replaceAll("_", "\\_")}%` : null;
    const rows = await this.db.select({ id: customers.id, externalReference: customers.externalReference, businessName: customers.businessName, contactName: customers.contactName, email: customers.email, phone: customers.phone, industry: customers.industry, websiteUrl: customers.websiteUrl, status: customers.status, creationSource: customers.creationSource, createdAt: customers.createdAt, updatedAt: customers.updatedAt }).from(customers).where(and(cursorCondition(customers.createdAt, customers.id, input.cursor), input.status ? eq(customers.status, input.status) : undefined, pattern ? or(like(customers.businessName, pattern), like(customers.contactName, pattern), like(customers.email, pattern), like(customers.externalReference, pattern), like(customers.phone, pattern)) : undefined)).orderBy(desc(customers.createdAt), desc(customers.id)).limit(input.limit + 1);
    return page(rows, input.limit);
  }
  async listSubscriptions(input: { cursor: CursorPosition | null; limit: number; status?: string; customerId?: string; planId?: string }) { const rows = await this.db.select({ subscription: subscriptions, customerName: customers.businessName, planCode: plans.code, planName: plans.name }).from(subscriptions).innerJoin(customers, eq(customers.id, subscriptions.customerId)).innerJoin(plans, eq(plans.id, subscriptions.planId)).where(and(cursorCondition(subscriptions.createdAt, subscriptions.id, input.cursor), input.status ? eq(subscriptions.status, input.status) : undefined, input.customerId ? eq(subscriptions.customerId, input.customerId) : undefined, input.planId ? eq(subscriptions.planId, input.planId) : undefined)).orderBy(desc(subscriptions.createdAt), desc(subscriptions.id)).limit(input.limit + 1); return page(rows.map((row) => ({ ...row.subscription, customerName: row.customerName, planCode: row.planCode, planName: row.planName })), input.limit); }
  async listDiscounts(input: { cursor: CursorPosition | null; limit: number; active?: boolean }) { const rows = await this.db.select().from(discounts).where(and(cursorCondition(discounts.createdAt, discounts.id, input.cursor), input.active == null ? undefined : eq(discounts.active, input.active))).orderBy(desc(discounts.createdAt), desc(discounts.id)).limit(input.limit + 1); return page(rows, input.limit); }
  async listPromotionCodes(input: { cursor: CursorPosition | null; limit: number; active?: boolean }) { const rows = await this.db.select({ promotion: promotionCodes, discountCode: discounts.code, discountName: discounts.name }).from(promotionCodes).innerJoin(discounts, eq(discounts.id, promotionCodes.discountId)).where(and(cursorCondition(promotionCodes.createdAt, promotionCodes.id, input.cursor), input.active == null ? undefined : eq(promotionCodes.active, input.active))).orderBy(desc(promotionCodes.createdAt), desc(promotionCodes.id)).limit(input.limit + 1); return page(rows.map((row) => ({ ...row.promotion, discountCode: row.discountCode, discountName: row.discountName })), input.limit); }
  async listAuditEvents(input: { cursor: CursorPosition | null; limit: number; action?: string; entityType?: string }) { const rows = await this.db.select().from(auditEvents).where(and(cursorCondition(auditEvents.createdAt, auditEvents.id, input.cursor), input.action ? eq(auditEvents.action, input.action.toUpperCase()) : undefined, input.entityType ? eq(auditEvents.entityType, input.entityType.toUpperCase()) : undefined)).orderBy(desc(auditEvents.createdAt), desc(auditEvents.id)).limit(input.limit + 1); return page(rows, input.limit); }
}

function cursorCondition(createdAt: AnySQLiteColumn, id: AnySQLiteColumn, cursor: CursorPosition | null) { return cursor ? or(lt(createdAt, cursor.createdAt), and(eq(createdAt, cursor.createdAt), lt(id, cursor.id))) : undefined; }
function page<T extends { id: string; createdAt: Date }>(rows: T[], limit: number): ApiPage<Record<string, unknown>> { const hasMore = rows.length > limit; const items = rows.slice(0, limit); const last = items.at(-1); return { items, next: hasMore && last ? { createdAt: last.createdAt, id: last.id } : null }; }
function publicPlan(plan: typeof plans.$inferSelect): Record<string, unknown> { return { code: plan.code, name: plan.name, description: plan.description, featured: plan.featured, displayOrder: plan.displayOrder, taxDisclosure: PUBLIC_PRICE_TAX_DISCLOSURE, prices: [], features: [] }; }
