import { and, eq, sql } from "drizzle-orm";
import type { AppDatabase } from "../../../db/index.ts";
import { idempotencyKeys, serviceCredentials, serviceRateLimits } from "../../../db/schema.ts";
import { DomainConflictError } from "../../shared/domain/errors.ts";
import { EntityId } from "../../shared/domain/value-objects.ts";
import type { ApiSecurityRepository } from "../application/ports.ts";
import { ServiceCredential, type IdempotencyRecord, type ServiceScope } from "../domain/api-security.ts";

export class D1ApiSecurityRepository implements ApiSecurityRepository {
  constructor(private readonly db: AppDatabase) {}
  async createCredential(value: ServiceCredential) { await this.db.insert(serviceCredentials).values(values(value)); }
  async rotateCredential(previous: ServiceCredential, next: ServiceCredential) { const p = previous.props; await this.db.batch([this.db.update(serviceCredentials).set({ status: p.status, revokedAt: p.revokedAt, revokedByAdminUserId: p.revokedByAdminUserId?.value ?? null, updatedAt: p.updatedAt }).where(and(eq(serviceCredentials.id, p.id.value), eq(serviceCredentials.status, "ACTIVE"))), this.db.insert(serviceCredentials).values(values(next))]); }
  async revokeCredential(value: ServiceCredential) { const p = value.props; await this.db.update(serviceCredentials).set({ status: p.status, revokedAt: p.revokedAt, revokedByAdminUserId: p.revokedByAdminUserId?.value ?? null, updatedAt: p.updatedAt }).where(eq(serviceCredentials.id, p.id.value)); }
  async findCredential(id: string) { const [row] = await this.db.select().from(serviceCredentials).where(eq(serviceCredentials.id, id)).limit(1); return row ? new ServiceCredential({ id: new EntityId(row.id), name: row.name, secretHash: row.secretHash, scopes: row.scopes as ServiceScope[], status: row.status as "ACTIVE" | "REVOKED", expiresAt: row.expiresAt, rotatedFromId: row.rotatedFromId ? new EntityId(row.rotatedFromId) : null, createdByAdminUserId: new EntityId(row.createdByAdminUserId), lastUsedAt: row.lastUsedAt, revokedAt: row.revokedAt, revokedByAdminUserId: row.revokedByAdminUserId ? new EntityId(row.revokedByAdminUserId) : null, createdAt: row.createdAt, updatedAt: row.updatedAt }) : null; }
  async markCredentialUsed(id: string, at: Date) { await this.db.update(serviceCredentials).set({ lastUsedAt: at, updatedAt: at }).where(eq(serviceCredentials.id, id)); }
  async consumeRateLimit(credentialId: string, windowStartedAt: Date, at: Date) { await this.db.insert(serviceRateLimits).values({ credentialId, windowStartedAt, requestCount: 1, updatedAt: at }).onConflictDoUpdate({ target: [serviceRateLimits.credentialId, serviceRateLimits.windowStartedAt], set: { requestCount: sql`${serviceRateLimits.requestCount} + 1`, updatedAt: at } }); const [row] = await this.db.select({ count: serviceRateLimits.requestCount }).from(serviceRateLimits).where(and(eq(serviceRateLimits.credentialId, credentialId), eq(serviceRateLimits.windowStartedAt, windowStartedAt))).limit(1); return row?.count ?? 0; }
  async claimIdempotency(value: IdempotencyRecord) { try { await this.insertIdempotency(value); return value; } catch (error) { const existing = await this.findIdempotency(value.scope, value.key); if (!existing) throw error; if (existing.expiresAt <= value.createdAt) { await this.db.delete(idempotencyKeys).where(and(eq(idempotencyKeys.id, existing.id), eq(idempotencyKeys.expiresAt, existing.expiresAt))); try { await this.insertIdempotency(value); return value; } catch (replacementError) { const concurrent = await this.findIdempotency(value.scope, value.key); if (concurrent) return concurrent; throw replacementError; } } return existing; } }
  async completeIdempotency(id: string, status: number, body: unknown, at: Date) { const result = await this.db.update(idempotencyKeys).set({ state: "COMPLETED", responseStatus: status, responseBody: body, updatedAt: at }).where(and(eq(idempotencyKeys.id, id), eq(idempotencyKeys.state, "PROCESSING"))); if (Number(result.meta.changes) !== 1) throw new DomainConflictError("IDEMPOTENCY_COMPLETION_CONFLICT", "Idempotency record changed concurrently."); }
  async releaseIdempotency(id: string) { await this.db.delete(idempotencyKeys).where(and(eq(idempotencyKeys.id, id), eq(idempotencyKeys.state, "PROCESSING"))); }
  private insertIdempotency(value: IdempotencyRecord) { return this.db.insert(idempotencyKeys).values({ id: value.id, scope: value.scope, key: value.key, requestHash: value.requestHash, state: value.state, responseStatus: value.responseStatus, responseBody: value.responseBody, expiresAt: value.expiresAt, createdAt: value.createdAt, updatedAt: value.updatedAt }); }
  private async findIdempotency(scope: string, key: string): Promise<IdempotencyRecord | null> { const [row] = await this.db.select().from(idempotencyKeys).where(and(eq(idempotencyKeys.scope, scope), eq(idempotencyKeys.key, key))).limit(1); return row ? { ...row, state: row.state as "PROCESSING" | "COMPLETED" } : null; }
}

function values(value: ServiceCredential) { const p = value.props; return { id: p.id.value, name: p.name, secretHash: p.secretHash, scopes: [...p.scopes], status: p.status, expiresAt: p.expiresAt, rotatedFromId: p.rotatedFromId?.value ?? null, createdByAdminUserId: p.createdByAdminUserId.value, lastUsedAt: p.lastUsedAt, revokedAt: p.revokedAt, revokedByAdminUserId: p.revokedByAdminUserId?.value ?? null, createdAt: p.createdAt, updatedAt: p.updatedAt }; }
