import { and, asc, desc, eq, gt, isNull, like, lt, lte, or } from "drizzle-orm";
import type { AnySQLiteColumn } from "drizzle-orm/sqlite-core";
import { PUBLIC_PRICE_TAX_DISCLOSURE } from "../../pricing/domain/tax-policy.ts";
import type { AppDatabase } from "../../../db/index.ts";
import { auditEvents, customers, discounts, invoices, notificationDeliveries, notificationTemplates, offerings, planFeatures, planPrices, plans, promotionCodes, subscriptions } from "../../../db/schema.ts";
import type { ApiPage, ApiReadRepository, AuditEventListDto, CursorPosition, CustomerListDto, DiscountListDto, InvoiceListDto, NotificationListDto, OfferingDto, PageInput, PlanDto, PlanPriceDto, PromotionCodeListDto, SubscriptionListDto } from "../application/read-ports.ts";

export class D1ApiReadRepository implements ApiReadRepository {
  constructor(private readonly db: AppDatabase) {}

  async listPublicPlans(at: Date) {
    const rows = await this.db.select({ plan: plans, price: planPrices }).from(plans).leftJoin(planPrices, and(eq(planPrices.planId, plans.id), eq(planPrices.active, true), lte(planPrices.effectiveFrom, at), or(isNull(planPrices.effectiveTo), gt(planPrices.effectiveTo, at)))).where(and(eq(plans.active, true), eq(plans.custom, false))).orderBy(plans.displayOrder, plans.code, planPrices.billingInterval);
    const features = await this.db.select({ planId: planFeatures.planId, code: offerings.code, name: offerings.name, included: planFeatures.included, limitValue: planFeatures.limitValue, limitUnit: planFeatures.limitUnit }).from(planFeatures).innerJoin(offerings, eq(offerings.id, planFeatures.offeringId)).where(eq(offerings.active, true)).orderBy(offerings.displayOrder);
    const grouped = new Map<string, Record<string, unknown>>();
    for (const row of rows) { const current = grouped.get(row.plan.id) ?? publicPlan(row.plan); if (row.price) (current.prices as unknown[]).push({ billingInterval: row.price.billingInterval, amountMinor: row.price.amountMinor, setupFeeMinor: row.price.setupFeeMinor, currency: row.price.currency, taxBehaviour: row.price.taxBehaviour }); grouped.set(row.plan.id, current); }
    for (const feature of features) { const plan = grouped.get(feature.planId); if (plan) (plan.features as unknown[]).push({ code: feature.code, name: feature.name, included: feature.included, limitValue: feature.limitValue, limitUnit: feature.limitUnit }); }
    return [...grouped.values()];
  }

  async getPublicPlan(code: string, at: Date) { return (await this.listPublicPlans(at)).find((plan) => plan.code === code.trim().toLowerCase()) ?? null; }

  listPlans(): Promise<PlanDto[]> { return this.db.select({ id: plans.id, code: plans.code, name: plans.name, description: plans.description, active: plans.active, featured: plans.featured, custom: plans.custom, displayOrder: plans.displayOrder, createdAt: plans.createdAt, updatedAt: plans.updatedAt }).from(plans).orderBy(plans.displayOrder, plans.name); }
  listOfferings(): Promise<OfferingDto[]> { return this.db.select({ id: offerings.id, code: offerings.code, name: offerings.name, description: offerings.description, category: offerings.category, active: offerings.active, displayOrder: offerings.displayOrder, createdAt: offerings.createdAt, updatedAt: offerings.updatedAt }).from(offerings).orderBy(offerings.displayOrder, offerings.name); }
  listPrices(): Promise<PlanPriceDto[]> { return this.db.select({ id: planPrices.id, planId: planPrices.planId, planName: plans.name, billingInterval: planPrices.billingInterval, amountMinor: planPrices.amountMinor, setupFeeMinor: planPrices.setupFeeMinor, currency: planPrices.currency, taxBehaviour: planPrices.taxBehaviour, effectiveFrom: planPrices.effectiveFrom, effectiveTo: planPrices.effectiveTo, active: planPrices.active, createdAt: planPrices.createdAt }).from(planPrices).innerJoin(plans, eq(plans.id, planPrices.planId)).orderBy(plans.displayOrder, desc(planPrices.effectiveFrom)); }

  async listCustomers(input: PageInput & { status?: string; query?: string }) {
    const query = input.query?.trim().slice(0, 120); const pattern = query ? `%${query.replaceAll("%", "\\%").replaceAll("_", "\\_")}%` : null;
    const rows = await this.db.select({ id: customers.id, externalReference: customers.externalReference, businessName: customers.businessName, contactName: customers.contactName, email: customers.email, phone: customers.phone, industry: customers.industry, websiteUrl: customers.websiteUrl, status: customers.status, creationSource: customers.creationSource, createdAt: customers.createdAt, updatedAt: customers.updatedAt }).from(customers).where(and(cursorCondition(customers.createdAt, customers.id, input.cursor), input.status ? eq(customers.status, input.status) : undefined, pattern ? or(like(customers.businessName, pattern), like(customers.contactName, pattern), like(customers.email, pattern), like(customers.externalReference, pattern), like(customers.phone, pattern)) : undefined)).orderBy(...order(input, customers.createdAt, customers.id)).limit(input.limit + 1);
    return page<CustomerListDto>(rows, input);
  }

  async listSubscriptions(input: PageInput & { status?: string; customerId?: string; planId?: string }) {
    const rows = await this.db.select({ id: subscriptions.id, customerId: subscriptions.customerId, customerName: customers.businessName, planId: subscriptions.planId, planCode: plans.code, planName: plans.name, status: subscriptions.status, billingInterval: subscriptions.billingInterval, currency: subscriptions.currency, startedAt: subscriptions.startedAt, currentPeriodStart: subscriptions.currentPeriodStart, currentPeriodEnd: subscriptions.currentPeriodEnd, gracePeriodEndsAt: subscriptions.gracePeriodEndsAt, serviceExtendedUntil: subscriptions.serviceExtendedUntil, cancelAt: subscriptions.cancelAt, cancelledAt: subscriptions.cancelledAt, trialEndsAt: subscriptions.trialEndsAt, version: subscriptions.version, createdAt: subscriptions.createdAt, updatedAt: subscriptions.updatedAt }).from(subscriptions).innerJoin(customers, eq(customers.id, subscriptions.customerId)).innerJoin(plans, eq(plans.id, subscriptions.planId)).where(and(cursorCondition(subscriptions.createdAt, subscriptions.id, input.cursor), input.status ? eq(subscriptions.status, input.status) : undefined, input.customerId ? eq(subscriptions.customerId, input.customerId) : undefined, input.planId ? eq(subscriptions.planId, input.planId) : undefined)).orderBy(...order(input, subscriptions.createdAt, subscriptions.id)).limit(input.limit + 1);
    return page<SubscriptionListDto>(rows, input);
  }

  async listInvoices(input: PageInput & { status?: string; customerId?: string; subscriptionId?: string }) {
    const rows = await this.db.select({ id: invoices.id, customerId: invoices.customerId, customerName: customers.businessName, subscriptionId: invoices.subscriptionId, invoiceNumber: invoices.invoiceNumber, status: invoices.status, currency: invoices.currency, subtotalMinor: invoices.subtotalMinor, taxMinor: invoices.taxMinor, totalMinor: invoices.totalMinor, amountDueMinor: invoices.amountDueMinor, issuedAt: invoices.issuedAt, dueAt: invoices.dueAt, paidAt: invoices.paidAt, createdAt: invoices.createdAt, updatedAt: invoices.updatedAt }).from(invoices).innerJoin(customers, eq(customers.id, invoices.customerId)).where(and(cursorCondition(invoices.createdAt, invoices.id, input.cursor), input.status ? eq(invoices.status, input.status) : undefined, input.customerId ? eq(invoices.customerId, input.customerId) : undefined, input.subscriptionId ? eq(invoices.subscriptionId, input.subscriptionId) : undefined)).orderBy(...order(input, invoices.createdAt, invoices.id)).limit(input.limit + 1);
    return page<InvoiceListDto>(rows, input);
  }

  async listDiscounts(input: PageInput & { active?: boolean }) {
    const rows = await this.db.select({ id: discounts.id, code: discounts.code, name: discounts.name, description: discounts.description, discountType: discounts.discountType, percentOffBasisPoints: discounts.percentOffBasisPoints, amountOffMinor: discounts.amountOffMinor, currency: discounts.currency, durationType: discounts.durationType, durationMonths: discounts.durationMonths, startsAt: discounts.startsAt, endsAt: discounts.endsAt, maxRedemptions: discounts.maxRedemptions, active: discounts.active, stackable: discounts.stackable, createdAt: discounts.createdAt, updatedAt: discounts.updatedAt }).from(discounts).where(and(cursorCondition(discounts.createdAt, discounts.id, input.cursor), input.active == null ? undefined : eq(discounts.active, input.active))).orderBy(...order(input, discounts.createdAt, discounts.id)).limit(input.limit + 1);
    return page<DiscountListDto>(rows, input);
  }

  async listPromotionCodes(input: PageInput & { active?: boolean }) {
    const rows = await this.db.select({ id: promotionCodes.id, discountId: promotionCodes.discountId, discountCode: discounts.code, discountName: discounts.name, code: promotionCodes.code, customerId: promotionCodes.customerId, planId: promotionCodes.planId, startsAt: promotionCodes.startsAt, expiresAt: promotionCodes.expiresAt, maxRedemptions: promotionCodes.maxRedemptions, redemptionCount: promotionCodes.redemptionCount, firstPurchaseOnly: promotionCodes.firstPurchaseOnly, active: promotionCodes.active, createdAt: promotionCodes.createdAt, updatedAt: promotionCodes.updatedAt }).from(promotionCodes).innerJoin(discounts, eq(discounts.id, promotionCodes.discountId)).where(and(cursorCondition(promotionCodes.createdAt, promotionCodes.id, input.cursor), input.active == null ? undefined : eq(promotionCodes.active, input.active))).orderBy(...order(input, promotionCodes.createdAt, promotionCodes.id)).limit(input.limit + 1);
    return page<PromotionCodeListDto>(rows, input);
  }

  async listNotifications(input: PageInput & { status?: string; channel?: string; customerId?: string; code?: string }) {
    const rows = await this.db.select({ id: notificationDeliveries.id, code: notificationTemplates.code, customerId: notificationDeliveries.customerId, recipientType: notificationDeliveries.recipientType, channel: notificationDeliveries.channel, status: notificationDeliveries.status, scheduledFor: notificationDeliveries.scheduledFor, attemptCount: notificationDeliveries.attemptCount, maxAttempts: notificationDeliveries.maxAttempts, nextAttemptAt: notificationDeliveries.nextAttemptAt, sentAt: notificationDeliveries.sentAt, cancelledAt: notificationDeliveries.cancelledAt, readAt: notificationDeliveries.readAt, errorCategory: notificationDeliveries.errorCategory, createdAt: notificationDeliveries.createdAt, updatedAt: notificationDeliveries.updatedAt }).from(notificationDeliveries).innerJoin(notificationTemplates, eq(notificationTemplates.id, notificationDeliveries.templateId)).where(and(cursorCondition(notificationDeliveries.createdAt, notificationDeliveries.id, input.cursor), input.status ? eq(notificationDeliveries.status, input.status) : undefined, input.channel ? eq(notificationDeliveries.channel, input.channel) : undefined, input.customerId ? eq(notificationDeliveries.customerId, input.customerId) : undefined, input.code ? eq(notificationTemplates.code, input.code) : undefined)).orderBy(...order(input, notificationDeliveries.createdAt, notificationDeliveries.id)).limit(input.limit + 1);
    return page<NotificationListDto>(rows, input);
  }

  async listAuditEvents(input: PageInput & { action?: string; entityType?: string }) {
    const rows = await this.db.select({ id: auditEvents.id, actorType: auditEvents.actorType, actorId: auditEvents.actorId, action: auditEvents.action, entityType: auditEvents.entityType, entityId: auditEvents.entityId, before: auditEvents.beforeJson, after: auditEvents.afterJson, requestId: auditEvents.requestId, createdAt: auditEvents.createdAt }).from(auditEvents).where(and(cursorCondition(auditEvents.createdAt, auditEvents.id, input.cursor), input.action ? eq(auditEvents.action, input.action.toUpperCase()) : undefined, input.entityType ? eq(auditEvents.entityType, input.entityType.toUpperCase()) : undefined)).orderBy(...order(input, auditEvents.createdAt, auditEvents.id)).limit(input.limit + 1);
    return page<AuditEventListDto>(rows, input);
  }
}

function cursorCondition(createdAt: AnySQLiteColumn, id: AnySQLiteColumn, cursor: CursorPosition | null) { return cursor ? cursor.direction === "asc" ? or(gt(createdAt, cursor.createdAt), and(eq(createdAt, cursor.createdAt), gt(id, cursor.id))) : or(lt(createdAt, cursor.createdAt), and(eq(createdAt, cursor.createdAt), lt(id, cursor.id))) : undefined; }
function order(input: PageInput, createdAt: AnySQLiteColumn, id: AnySQLiteColumn) { const direction = input.direction === "asc" ? asc : desc; return [direction(createdAt), direction(id)] as const; }
function page<T extends { id: string; createdAt: Date }>(rows: T[], input: PageInput): ApiPage<T> { const hasMore = rows.length > input.limit; const items = rows.slice(0, input.limit); const last = items.at(-1); return { items, next: hasMore && last ? { createdAt: last.createdAt, id: last.id, direction: input.direction } : null }; }
function publicPlan(plan: typeof plans.$inferSelect): Record<string, unknown> { return { code: plan.code, name: plan.name, description: plan.description, featured: plan.featured, displayOrder: plan.displayOrder, taxDisclosure: PUBLIC_PRICE_TAX_DISCLOSURE, prices: [], features: [] }; }
