import type { AuditRecorder } from "../../audit/application/ports.ts";
import { AUDIT_ACTIONS } from "../../audit/domain/audit-event.ts";
import { OperationalQueueItem } from "../../operations/domain/operational-queue.ts";
import type { Clock, IdGenerator } from "../../shared/application/ports.ts";
import { DomainConflictError } from "../../shared/domain/errors.ts";
import { EntityId, StableCode } from "../../shared/domain/value-objects.ts";
import type { AgentProvisioner, AgentProvisioningRepository } from "./ports.ts";
import { AgentLink, AgentProvisioningJob, type AgentOperation } from "../domain/agent-provisioning.ts";
export class RequestAgentProvisioningService { constructor(private readonly repository: AgentProvisioningRepository, private readonly ids: IdGenerator, private readonly clock: Clock, private readonly audit: AuditRecorder) {} async execute(input: { customerId: string; platform: string; operation: AgentOperation; idempotencyKey: string }) { const existingJob = await this.repository.findJobByIdempotencyKey(input.idempotencyKey); if (existingJob) return existingJob; const now = this.clock.now(); const platform = new StableCode(input.platform); const currentLink = await this.repository.findLink(input.customerId, platform.value); if (!currentLink && input.operation !== "PROVISION") throw new DomainConflictError("AGENT_LINK_NOT_FOUND", "Agent link must be provisioned first."); const baseLink = currentLink ?? new AgentLink({ id: new EntityId(this.ids.next()), customerId: new EntityId(input.customerId), agentPlatform: platform, externalAgentId: null, status: "NOT_PROVISIONED", lastSyncedAt: null, version: 1, createdAt: now, updatedAt: now }); const link = baseLink.request(now); const job = new AgentProvisioningJob({ id: new EntityId(this.ids.next()), agentLinkId: link.props.id, customerId: link.props.customerId, operation: input.operation, status: "PENDING", idempotencyKey: input.idempotencyKey, attemptCount: 0, maxAttempts: 5, nextAttemptAt: now, errorCategory: null, requestedAt: now, startedAt: null, completedAt: null, version: 1, createdAt: now, updatedAt: now }); const queue = new OperationalQueueItem({ id: new EntityId(this.ids.next()), queueType: "AGENT_PROVISIONING", sourceType: "AGENT_PROVISIONING_JOB", sourceId: job.props.id.value, customerId: link.props.customerId, status: "OPEN", priority: 30, title: `${input.operation.toLowerCase()} ${platform.value} agent`, availableAt: now, dueAt: null, assignedToAdminUserId: null, claimedAt: null, resolvedAt: null, version: 1, createdAt: now, updatedAt: now }); await this.repository.createRequest(link, currentLink?.props.version ?? null, job, queue); await this.audit.record({ action: AUDIT_ACTIONS.agentProvisioningRequested, entityType: "AGENT_PROVISIONING_JOB", entityId: job.props.id.value, after: { link: link.props, job: job.props } }); return job; } }
export class RunAgentProvisioningService { constructor(private readonly repository: AgentProvisioningRepository, private readonly provider: AgentProvisioner, private readonly clock: Clock, private readonly audit: AuditRecorder) {} async execute() { const pending = await this.repository.findReadyJob(this.clock.now()); if (!pending) return null; const started = pending.start(this.clock.now()); await this.repository.startJob(started, pending.props.version); const link = await this.repository.findLinkById(started.props.agentLinkId.value); if (!link) throw new DomainConflictError("AGENT_LINK_NOT_FOUND", "Agent link does not exist."); try { const outcome = await this.provider.execute({ operation: started.props.operation, platform: link.props.agentPlatform.value, customerId: link.props.customerId.value, externalAgentId: link.props.externalAgentId, idempotencyKey: started.props.idempotencyKey }); const now = this.clock.now(); const nextLink = link.succeeded(started.props.operation, outcome.externalAgentId, now); const succeeded = started.succeed(now); await this.repository.saveOutcome(nextLink, link.props.version, succeeded, started.props.version, true); await this.audit.record({ action: AUDIT_ACTIONS.agentProvisioningSucceeded, entityType: "AGENT_PROVISIONING_JOB", entityId: succeeded.props.id.value, before: started.props, after: succeeded.props }); return succeeded; } catch (error) { const now = this.clock.now(); const retryAt = started.props.attemptCount < started.props.maxAttempts ? new Date(now.getTime() + 60_000 * 2 ** (started.props.attemptCount - 1)) : null; const failed = started.fail("PROVIDER_ERROR", retryAt, now); const terminal = failed.props.status === "FAILED"; await this.repository.saveOutcome(terminal ? link.failed(now) : link, link.props.version, failed, started.props.version, terminal); await this.audit.record({ action: terminal ? AUDIT_ACTIONS.agentProvisioningFailed : AUDIT_ACTIONS.agentProvisioningRetryScheduled, entityType: "AGENT_PROVISIONING_JOB", entityId: failed.props.id.value, before: started.props, after: failed.props }); throw error; } } }
