import { AgentIntegrationService } from "@/modules/agent/application/agent-integration-service";
import { ReconcileAgentPlatformService, RequestAgentProvisioningService, SynchronizeAgentLinkService } from "@/modules/agent/application/agent-provisioning-services";
import type { AgentOperation } from "@/modules/agent/domain/agent-provisioning";
import { D1AgentIntegrationRepository } from "@/modules/agent/infrastructure/d1-agent-integration-repository";
import { D1AgentProvisioningRepository } from "@/modules/agent/infrastructure/d1-agent-provisioning-repository";
import { configuredAgentProvisioner } from "@/modules/agent/infrastructure/http-agent-platform-provisioner";
import { EntitlementService } from "@/modules/subscription/application/subscription-services";
import { D1SubscriptionRepository } from "@/modules/subscription/infrastructure/d1-subscription-repository";
import { AuthorizationDeniedError, DomainConflictError } from "@/modules/shared/domain/errors";
import type { ServicePrincipal, ServiceScope } from "@/modules/api/domain/api-security";
import { apiRoute, assertAllowedFields, dataResponse, idempotentResponse, jsonObject, optionalString, requiredString } from "../../../../../api-http";
import { authenticateService, createApiRuntime } from "../../../../../api-runtime";

type Context = { params: Promise<{ customerId: string; resource: string }> };

export async function GET(request: Request, context: Context) { return apiRoute(request, async ({ requestId }) => { const { customerId, resource } = await context.params; const runtime = await createApiRuntime(request, requestId); const validation = resource === "entitlements" || resource === "subscription-validation"; const required = validation ? "subscription:validate" : resource === "bootstrap" ? "customer:read" : null; if (!required) throw new DomainConflictError("API_ROUTE_NOT_FOUND", "API route does not exist."); const { principal } = await authenticateService(runtime, request, required); requireScopes(principal, resource === "bootstrap" ? ["subscription:validate", "entitlement:read"] : ["entitlement:read"]); const service = new AgentIntegrationService(new D1AgentIntegrationRepository(runtime.db), new EntitlementService(new D1SubscriptionRepository(runtime.db), runtime.clock)); return dataResponse(resource === "bootstrap" ? await service.buildBootstrapProfile(customerId) : await service.validateSubscription(customerId), 200, { "cache-control": "private, no-store" }); }); }

export async function POST(request: Request, context: Context) { return apiRoute(request, async ({ requestId }) => { const { customerId, resource } = await context.params; if (!["provisioning-jobs", "reconciliation"].includes(resource)) throw new DomainConflictError("API_ROUTE_NOT_FOUND", "API route does not exist."); const runtime = await createApiRuntime(request, requestId); const { principal, audit } = await authenticateService(runtime, request, "agent-link:write"); const body = await jsonObject(request); const repository = new D1AgentProvisioningRepository(runtime.db); const platform = requiredString(body, "platform", 80); if (resource === "reconciliation") { assertAllowedFields(body, ["platform"]); return idempotentResponse({ request, requestId, scope: `service:${principal.credentialId}:agent:${customerId}:reconciliation`, body, repository: runtime.security, ids: runtime.ids, clock: runtime.clock, execute: async () => { const entitlement = new EntitlementService(new D1SubscriptionRepository(runtime.db), runtime.clock); const requestService = new RequestAgentProvisioningService(repository, runtime.ids, runtime.clock, audit); const synchronize = new SynchronizeAgentLinkService(repository, runtime.ids, runtime.clock, audit); const result = await new ReconcileAgentPlatformService(repository, entitlement, await configuredAgentProvisioner(), requestService, synchronize).execute({ customerId, platform, idempotencyKey: request.headers.get("idempotency-key")! }); return dataResponse(result); } }); } assertAllowedFields(body, ["platform", "operation"]); return idempotentResponse({ request, requestId, scope: `service:${principal.credentialId}:agent:${customerId}:provisioning`, body, repository: runtime.security, ids: runtime.ids, clock: runtime.clock, execute: async () => { const job = await new RequestAgentProvisioningService(repository, runtime.ids, runtime.clock, audit).execute({ customerId, platform, operation: requiredString(body, "operation", 20) as AgentOperation, idempotencyKey: request.headers.get("idempotency-key")! }); const p = job.props; return dataResponse({ id: p.id.value, customerId: p.customerId.value, agentLinkId: p.agentLinkId.value, operation: p.operation, status: p.status, attemptCount: p.attemptCount, requestedAt: p.requestedAt }, 202); } }); }); }

export async function PATCH(request: Request, context: Context) { return apiRoute(request, async ({ requestId }) => { const { customerId, resource } = await context.params; if (resource !== "agent-link") throw new DomainConflictError("API_ROUTE_NOT_FOUND", "API route does not exist."); const runtime = await createApiRuntime(request, requestId); const { principal, audit } = await authenticateService(runtime, request, "agent-link:write"); const body = await jsonObject(request); assertAllowedFields(body, ["platform", "externalAgentId", "status"]); return idempotentResponse({ request, requestId, scope: `service:${principal.credentialId}:agent:${customerId}:link`, body, repository: runtime.security, ids: runtime.ids, clock: runtime.clock, execute: async () => { const link = await new SynchronizeAgentLinkService(new D1AgentProvisioningRepository(runtime.db), runtime.ids, runtime.clock, audit).execute({ customerId, platform: requiredString(body, "platform", 80), externalAgentId: optionalString(body, "externalAgentId", 255), status: requiredString(body, "status", 20) as "ACTIVE" | "SUSPENDED" | "ERROR" }); const p = link.props; return dataResponse({ customerId: p.customerId.value, platform: p.agentPlatform.value, externalAgentId: p.externalAgentId, status: p.status, lastSyncedAt: p.lastSyncedAt, version: p.version }); } }); }); }

function requireScopes(principal: ServicePrincipal, scopes: ServiceScope[]) { const missing = scopes.find((scope) => !principal.scopes.has(scope)); if (missing) throw new AuthorizationDeniedError("SERVICE_SCOPE_REQUIRED", `Service scope ${missing} is required.`); }
