import type { AuditRecorder } from "../../audit/application/ports.ts";
import { AUDIT_ACTIONS } from "../../audit/domain/audit-event.ts";
import { OperationalQueueItem } from "../../operations/domain/operational-queue.ts";
import type { Clock, IdGenerator } from "../../shared/application/ports.ts";
import { DomainConflictError } from "../../shared/domain/errors.ts";
import { EntityId, StableCode } from "../../shared/domain/value-objects.ts";
import type { CustomerIntegrationRepository } from "./ports.ts";
import { CustomerIntegration, type CustomerIntegrationStatus } from "../domain/customer-integration.ts";

export class CustomerIntegrationService {
  constructor(private readonly repository: CustomerIntegrationRepository, private readonly ids: IdGenerator, private readonly clock: Clock, private readonly audit: AuditRecorder) {}
  async register(input: { customerId: string; integrationCode: string; category: string; metadata?: Readonly<Record<string, unknown>> }) { const code = new StableCode(input.integrationCode); if (await this.repository.findByCustomerAndCode(input.customerId, code.value)) throw new DomainConflictError("CUSTOMER_INTEGRATION_EXISTS", "Customer integration already exists."); const now = this.clock.now(); const value = new CustomerIntegration({ id: new EntityId(this.ids.next()), customerId: new EntityId(input.customerId), integrationCode: code, category: input.category, status: "NOT_CONNECTED", lastCheckedAt: null, lastSuccessfulAt: null, errorCode: null, metadata: input.metadata ?? {}, version: 1, createdAt: now, updatedAt: now }); await this.repository.create(value); await this.audit.record({ action: AUDIT_ACTIONS.customerIntegrationRegistered, entityType: "CUSTOMER_INTEGRATION", entityId: value.props.id.value, after: value.props }); return value; }
  async updateHealth(id: string, status: CustomerIntegrationStatus, errorCode: string | null = null, metadata?: Readonly<Record<string, unknown>>) { const current = await this.repository.findById(new EntityId(id).value); if (!current) throw new DomainConflictError("CUSTOMER_INTEGRATION_NOT_FOUND", "Customer integration does not exist."); const now = this.clock.now(); const next = current.update(status, now, errorCode, metadata); const queue = ["DEGRADED", "ERROR"].includes(status) ? new OperationalQueueItem({ id: new EntityId(this.ids.next()), queueType: "INTERNAL_ACTION", sourceType: "CUSTOMER_INTEGRATION", sourceId: id, customerId: current.props.customerId, status: "OPEN", priority: status === "ERROR" ? 20 : 40, title: `Resolve ${current.props.integrationCode.value} integration`, availableAt: now, dueAt: null, assignedToAdminUserId: null, claimedAt: null, resolvedAt: null, version: 1, createdAt: now, updatedAt: now }) : null; await this.repository.saveWithProjection(next, current.props.version, queue); await this.audit.record({ action: AUDIT_ACTIONS.customerIntegrationChanged, entityType: "CUSTOMER_INTEGRATION", entityId: id, before: current.props, after: next.props }); return next; }
}
