import { DomainValidationError } from "../../shared/domain/errors.ts";
import { EntityId, StableCode, optionalText, requireText } from "../../shared/domain/value-objects.ts";
export type AgentLinkStatus = "NOT_PROVISIONED" | "PENDING" | "ACTIVE" | "SUSPENDED" | "ERROR";
export type AgentOperation = "PROVISION" | "UPDATE" | "SUSPEND" | "RESUME";
export type AgentJobStatus = "PENDING" | "IN_PROGRESS" | "SUCCEEDED" | "FAILED" | "CANCELLED";
export type AgentLinkProps = { id: EntityId; customerId: EntityId; agentPlatform: StableCode; externalAgentId: string | null; status: AgentLinkStatus; lastSyncedAt: Date | null; version: number; createdAt: Date; updatedAt: Date };
export class AgentLink { readonly props: Readonly<AgentLinkProps>; constructor(input: AgentLinkProps) { if (!["NOT_PROVISIONED", "PENDING", "ACTIVE", "SUSPENDED", "ERROR"].includes(input.status)) throw new DomainValidationError("INVALID_AGENT_LINK_STATUS", "Agent link status is invalid."); if (["ACTIVE", "SUSPENDED"].includes(input.status) && !input.externalAgentId) throw new DomainValidationError("AGENT_REFERENCE_REQUIRED", "Active and suspended links require an external agent ID."); this.props = Object.freeze({ ...input, externalAgentId: optionalText(input.externalAgentId, "externalAgentId", 255) }); } request(at: Date) { return new AgentLink({ ...this.props, status: "PENDING", version: this.props.version + 1, updatedAt: at }); } succeeded(operation: AgentOperation, externalAgentId: string, at: Date) { return new AgentLink({ ...this.props, externalAgentId, status: operation === "SUSPEND" ? "SUSPENDED" : "ACTIVE", lastSyncedAt: at, version: this.props.version + 1, updatedAt: at }); } failed(at: Date) { return new AgentLink({ ...this.props, status: "ERROR", version: this.props.version + 1, updatedAt: at }); } }
export type AgentProvisioningJobProps = { id: EntityId; agentLinkId: EntityId; customerId: EntityId; operation: AgentOperation; status: AgentJobStatus; idempotencyKey: string; attemptCount: number; maxAttempts: number; nextAttemptAt: Date | null; errorCategory: string | null; requestedAt: Date; startedAt: Date | null; completedAt: Date | null; version: number; createdAt: Date; updatedAt: Date };
export class AgentProvisioningJob { readonly props: Readonly<AgentProvisioningJobProps>; constructor(input: AgentProvisioningJobProps) { if (!["PROVISION", "UPDATE", "SUSPEND", "RESUME"].includes(input.operation) || !["PENDING", "IN_PROGRESS", "SUCCEEDED", "FAILED", "CANCELLED"].includes(input.status)) throw new DomainValidationError("INVALID_AGENT_JOB", "Agent provisioning job is invalid."); if (!Number.isSafeInteger(input.attemptCount) || input.attemptCount < 0 || !Number.isSafeInteger(input.maxAttempts) || input.maxAttempts < 1 || input.attemptCount > input.maxAttempts) throw new DomainValidationError("INVALID_AGENT_ATTEMPTS", "Agent provisioning attempts are invalid."); this.props = Object.freeze({ ...input, idempotencyKey: requireText(input.idempotencyKey, "idempotencyKey", 255), errorCategory: optionalText(input.errorCategory, "errorCategory", 120) }); } start(at: Date) { return new AgentProvisioningJob({ ...this.props, status: "IN_PROGRESS", startedAt: at, nextAttemptAt: null, attemptCount: this.props.attemptCount + 1, version: this.props.version + 1, updatedAt: at }); } succeed(at: Date) { return new AgentProvisioningJob({ ...this.props, status: "SUCCEEDED", completedAt: at, errorCategory: null, version: this.props.version + 1, updatedAt: at }); } fail(errorCategory: string, retryAt: Date | null, at: Date) { const terminal = !retryAt || this.props.attemptCount >= this.props.maxAttempts; return new AgentProvisioningJob({ ...this.props, status: terminal ? "FAILED" : "PENDING", completedAt: terminal ? at : null, errorCategory: terminal ? errorCategory : null, nextAttemptAt: terminal ? null : retryAt, version: this.props.version + 1, updatedAt: at }); } }
