import { AdminAuthorizationGuard } from "@/modules/identity/application/access-control-services";
import type { PermissionCode } from "@/modules/identity/domain/access-control";
import { CreateCustomerService } from "@/modules/customer/application/customer-services";
import { D1CustomerRepository } from "@/modules/customer/infrastructure/d1-customer-repositories";
import { CatalogueManagementService } from "@/modules/catalogue/application/catalogue-services";
import { D1CatalogueRepository } from "@/modules/catalogue/infrastructure/d1-catalogue-repository";
import { CreatePriceOverrideService, PricingService, PreviewPriceService, PublishPlanPriceService } from "@/modules/pricing/application/pricing-services";
import type { BillingInterval, TaxBehaviour } from "@/modules/pricing/domain/pricing";
import { AustralianGstPolicy } from "@/modules/pricing/domain/tax-policy";
import { D1PricingRepository } from "@/modules/pricing/infrastructure/d1-pricing-repository";
import { ApplyCustomerDiscountService, CreateDiscountService, CreatePromotionCodeService, CryptoPromotionCodeGenerator, DiscountPricingAdapter } from "@/modules/discount/application/discount-services";
import type { DiscountDuration, DiscountType } from "@/modules/discount/domain/discount";
import { D1DiscountRepository } from "@/modules/discount/infrastructure/d1-discount-repository";
import { CreateSubscriptionService, SubscriptionLifecycleService } from "@/modules/subscription/application/subscription-services";
import type { SubscriptionStatus } from "@/modules/subscription/domain/subscription";
import { D1SubscriptionRepository } from "@/modules/subscription/infrastructure/d1-subscription-repository";
import { AddBillingNoteService, CustomerBillingOverviewService, UpdateCustomerBillingProfileService } from "@/modules/billing/application/billing-operations-services";
import { D1BillingRepository } from "@/modules/billing/infrastructure/d1-billing-repository";
import { ManageServiceCredentialService, parseServiceScopes } from "@/modules/api/application/api-security-services";
import { DomainConflictError } from "@/modules/shared/domain/errors";
import { apiRoute, dataResponse, idempotentResponse, jsonObject, oneOfFilter, optionalBoolean, optionalBooleanField, optionalDate, optionalInteger, optionalString, pageResponse, paginationFrom, requiredDate, requiredInteger, requiredString } from "../../api-http";
import { authenticateAdmin, createApiRuntime, type ApiRuntime } from "../../api-runtime";

type Context = { params: Promise<{ segments: string[] }> };

export async function GET(request: Request, context: Context) { return apiRoute(request, async ({ requestId }) => { const segments = (await context.params).segments; const runtime = await createApiRuntime(request, requestId); await authenticateAdmin(runtime, readPermission(segments)); const url = new URL(request.url); const pagination = paginationFrom(url);
  if (segments[0] === "customers" && segments.length === 1) { const page = await runtime.read.listCustomers({ ...pagination, status: oneOfFilter(url.searchParams.get("status"), ["PROSPECT", "ACTIVE", "SUSPENDED", "CANCELLED", "ARCHIVED"] as const, "status"), query: url.searchParams.get("q") ?? undefined }); return pageResponse(page.items, page.next); }
  if (segments[0] === "customers" && segments.length === 3 && segments[2] === "billing") { if (!await new D1PricingRepository(runtime.db).customerExists(segments[1])) throw new DomainConflictError("CUSTOMER_NOT_FOUND", "Customer does not exist."); return dataResponse(billingOverviewDto(await new CustomerBillingOverviewService(new D1BillingRepository(runtime.db), new D1SubscriptionRepository(runtime.db), runtime.clock).execute(segments[1]))); }
  if (segments[0] === "customers" && segments.length === 2) return found(await runtime.portal.getAdminCustomer(segments[1]), "CUSTOMER_NOT_FOUND");
  if (segments[0] === "customers" && segments[2] === "pricing") { const customer = await runtime.portal.getAdminCustomer(segments[1]); if (!customer) throw new DomainConflictError("CUSTOMER_NOT_FOUND", "Customer does not exist."); return dataResponse({ subscription: customer.subscription, priceOverrides: customer.priceOverrides, discounts: customer.discounts }); }
  if (segments[0] === "plans") return dataResponse((await runtime.portal.getCatalogue()).plans);
  if (segments[0] === "offerings") return dataResponse((await runtime.portal.getCatalogue()).offerings);
  if (segments[0] === "prices") return dataResponse((await runtime.portal.getPricing()).prices);
  if (segments[0] === "discounts") { const page = await runtime.read.listDiscounts({ ...pagination, active: optionalBoolean(url.searchParams.get("active")) }); return pageResponse(page.items, page.next); }
  if (segments[0] === "promotion-codes") { const page = await runtime.read.listPromotionCodes({ ...pagination, active: optionalBoolean(url.searchParams.get("active")) }); return pageResponse(page.items, page.next); }
  if (segments[0] === "subscriptions" && segments.length === 1) { const page = await runtime.read.listSubscriptions({ ...pagination, status: oneOfFilter(url.searchParams.get("status"), ["PENDING", "TRIAL", "ACTIVE", "PAST_DUE", "SUSPENDED", "CANCEL_AT_PERIOD_END", "CANCELLED", "EXPIRED"] as const, "status"), customerId: url.searchParams.get("customerId") ?? undefined, planId: url.searchParams.get("planId") ?? undefined }); return pageResponse(page.items, page.next); }
  if (segments[0] === "subscriptions" && segments.length === 2) { const value = await new D1SubscriptionRepository(runtime.db).findById(segments[1]); return found(value ? subscriptionDto(value) : null, "SUBSCRIPTION_NOT_FOUND"); }
  if (segments[0] === "audit-events") { const page = await runtime.read.listAuditEvents({ ...pagination, action: url.searchParams.get("action") ?? undefined, entityType: url.searchParams.get("entityType") ?? undefined }); return pageResponse(page.items, page.next); }
  throw routeNotFound(); }); }

export async function POST(request: Request, context: Context) { return apiRoute(request, async ({ requestId }) => { const segments = (await context.params).segments; const runtime = await createApiRuntime(request, requestId); const { principal, audit } = await authenticateAdmin(runtime, writePermission(segments)); const body = await jsonObject(request); if (segments[0] === "service-credentials" || (segments[0] === "customers" && segments[2] === "pricing" && segments[3] === "preview")) return executePost(runtime, principal, audit, segments, body); return idempotentResponse({ request, requestId, scope: `admin:${segments.join(":")}:post`, body, repository: runtime.security, ids: runtime.ids, clock: runtime.clock, execute: () => executePost(runtime, principal, audit, segments, body) }); }); }

export async function PATCH(request: Request, context: Context) { return apiRoute(request, async ({ requestId }) => { const segments = (await context.params).segments; if (segments[0] !== "subscriptions" || segments.length !== 2) throw routeNotFound(); const runtime = await createApiRuntime(request, requestId); const { audit } = await authenticateAdmin(runtime, "SUBSCRIPTION_WRITE"); const body = await jsonObject(request); return idempotentResponse({ request, requestId, scope: `admin:subscriptions:${segments[1]}:patch`, body, repository: runtime.security, ids: runtime.ids, clock: runtime.clock, execute: async () => { const target = requiredString(body, "status", 30) as SubscriptionStatus; const lifecycle = new SubscriptionLifecycleService(new D1SubscriptionRepository(runtime.db), runtime.ids, runtime.clock, audit); const subscription = target === "PAST_DUE" ? await lifecycle.markPastDue(segments[1], requiredDate(body, "gracePeriodEndsAt")) : target === "CANCEL_AT_PERIOD_END" ? await lifecycle.scheduleCancellation(segments[1]) : await lifecycle.transition(segments[1], target); return dataResponse(subscriptionDto(subscription), 200); } }); }); }

export async function DELETE(request: Request, context: Context) { return apiRoute(request, async ({ requestId }) => { const segments = (await context.params).segments; if (segments[0] !== "service-credentials" || segments.length !== 2) throw routeNotFound(); const runtime = await createApiRuntime(request, requestId); const { principal, audit } = await authenticateAdmin(runtime, "ADMIN_USER_MANAGE"); const body = {}; return idempotentResponse({ request, requestId, scope: `admin:service-credentials:${segments[1]}:delete`, body, repository: runtime.security, ids: runtime.ids, clock: runtime.clock, execute: async () => { await new ManageServiceCredentialService(runtime.security, new AdminAuthorizationGuard(), runtime.ids, runtime.clock, audit).revoke(principal, segments[1]); return dataResponse({ revoked: true }); } }); }); }

async function executePost(runtime: ApiRuntime, principal: Awaited<ReturnType<typeof authenticateAdmin>>["principal"], audit: Awaited<ReturnType<typeof authenticateAdmin>>["audit"], segments: string[], body: Record<string, unknown>) {
  if (segments[0] === "customers" && segments.length === 1) { const customer = await new CreateCustomerService(new D1CustomerRepository(runtime.db), runtime.ids, runtime.clock, audit).execute({ externalReference: requiredString(body, "externalReference", 120), businessName: requiredString(body, "businessName", 200), contactName: requiredString(body, "contactName", 200), email: requiredString(body, "email", 320), phone: optionalString(body, "phone", 50), industry: optionalString(body, "industry", 120), websiteUrl: optionalString(body, "websiteUrl", 500), tradingName: optionalString(body, "tradingName", 200), abn: optionalString(body, "abn", 30), timezone: optionalString(body, "timezone", 80) ?? "Australia/Sydney", state: optionalString(body, "state", 80), suburb: optionalString(body, "suburb", 120), postcode: optionalString(body, "postcode", 20), creationSource: "ADMIN" }); return dataResponse(customerDto(customer), 201); }
  const catalogue = new CatalogueManagementService(new D1CatalogueRepository(runtime.db), runtime.ids, runtime.clock, audit);
  if (segments[0] === "plans") { const plan = await catalogue.createPlan({ code: requiredString(body, "code", 80), name: requiredString(body, "name", 160), description: optionalString(body, "description", 2_000), active: optionalBooleanField(body, "active", true), featured: optionalBooleanField(body, "featured", false), custom: optionalBooleanField(body, "custom", false), displayOrder: optionalInteger(body, "displayOrder") ?? 0 }); return dataResponse(planDto(plan), 201); }
  if (segments[0] === "offerings") { const offering = await catalogue.createOffering({ code: requiredString(body, "code", 80), name: requiredString(body, "name", 160), description: optionalString(body, "description", 2_000), category: requiredString(body, "category", 120), active: optionalBooleanField(body, "active", true), displayOrder: optionalInteger(body, "displayOrder") ?? 0 }); return dataResponse(offeringDto(offering), 201); }
  const pricingRepository = new D1PricingRepository(runtime.db);
  if (segments[0] === "prices") { const price = await new PublishPlanPriceService(pricingRepository, pricingRepository, runtime.ids, runtime.clock, audit).execute({ planId: requiredString(body, "planId", 80), billingInterval: requiredString(body, "billingInterval", 20) as BillingInterval, amountMinor: requiredInteger(body, "amountMinor"), setupFeeMinor: requiredInteger(body, "setupFeeMinor"), currency: requiredString(body, "currency", 3), taxBehaviour: requiredString(body, "taxBehaviour", 20) as TaxBehaviour, effectiveFrom: requiredDate(body, "effectiveFrom"), effectiveTo: optionalDate(body, "effectiveTo"), createdBy: principal.adminUserId }); return dataResponse(priceDto(price), 201); }
  if (segments[0] === "customers" && segments[2] === "price-overrides") { const override = await new CreatePriceOverrideService(pricingRepository, pricingRepository, runtime.ids, runtime.clock, audit).execute({ customerId: segments[1], planId: requiredString(body, "planId", 80), billingInterval: requiredString(body, "billingInterval", 20) as BillingInterval, amountMinor: requiredInteger(body, "amountMinor"), setupFeeMinor: requiredInteger(body, "setupFeeMinor"), currency: requiredString(body, "currency", 3), effectiveFrom: requiredDate(body, "effectiveFrom"), effectiveTo: optionalDate(body, "effectiveTo"), reason: requiredString(body, "reason", 500), createdBy: principal.adminUserId }); return dataResponse(overrideDto(override), 201); }
  const discountRepository = new D1DiscountRepository(runtime.db);
  const pricing = new PricingService(pricingRepository, new AustralianGstPolicy(), new DiscountPricingAdapter(discountRepository));
  if (segments[0] === "customers" && segments[2] === "pricing" && segments[3] === "preview") { const proposed = await new PreviewPriceService(pricing).execute({ customerId: segments[1], planId: requiredString(body, "planId", 80), billingInterval: requiredString(body, "billingInterval", 20) as BillingInterval, effectiveAt: optionalDate(body, "effectiveAt") ?? runtime.clock.now(), includeSetupFee: optionalBooleanField(body, "includeSetupFee", false) }); return dataResponse({ proposed, persistenceRequired: true }); }
  if (segments[0] === "discounts") { const discount = await new CreateDiscountService(discountRepository, runtime.ids, runtime.clock, audit).execute({ code: requiredString(body, "code", 80), name: requiredString(body, "name", 160), description: optionalString(body, "description", 2_000), discountType: requiredString(body, "discountType", 30) as DiscountType, percentOffBasisPoints: optionalInteger(body, "percentOffBasisPoints"), amountOffMinor: optionalInteger(body, "amountOffMinor"), currency: optionalString(body, "currency", 3), durationType: requiredString(body, "durationType", 30) as DiscountDuration, durationMonths: optionalInteger(body, "durationMonths"), startsAt: requiredDate(body, "startsAt"), endsAt: optionalDate(body, "endsAt"), maxRedemptions: optionalInteger(body, "maxRedemptions"), active: optionalBooleanField(body, "active", true), stackable: optionalBooleanField(body, "stackable", false), createdBy: principal.adminUserId }); return dataResponse(discountDto(discount), 201); }
  if (segments[0] === "promotion-codes") { const promotion = await new CreatePromotionCodeService(discountRepository, pricingRepository, new CryptoPromotionCodeGenerator(), runtime.ids, runtime.clock, audit).execute({ discountId: requiredString(body, "discountId", 80), code: optionalString(body, "code", 80), customerId: optionalString(body, "customerId", 80), planId: optionalString(body, "planId", 80), startsAt: requiredDate(body, "startsAt"), expiresAt: optionalDate(body, "expiresAt"), maxRedemptions: optionalInteger(body, "maxRedemptions"), firstPurchaseOnly: optionalBooleanField(body, "firstPurchaseOnly", false), active: optionalBooleanField(body, "active", true) }); return dataResponse(promotionDto(promotion), 201); }
  if (segments[0] === "customers" && segments[2] === "discounts") { const assignment = await new ApplyCustomerDiscountService(discountRepository, pricingRepository, runtime.ids, runtime.clock, audit).execute({ customerId: segments[1], discountId: requiredString(body, "discountId", 80), subscriptionId: optionalString(body, "subscriptionId", 80), effectiveFrom: requiredDate(body, "effectiveFrom"), source: "ADMIN", appliedBy: principal.adminUserId, reason: requiredString(body, "reason", 500) }); return dataResponse(customerDiscountDto(assignment), 201); }
  if (segments[0] === "customers" && segments[2] === "billing-profile") { const profile = await new UpdateCustomerBillingProfileService(new D1BillingRepository(runtime.db), pricingRepository, runtime.ids, runtime.clock, audit).execute({ customerId: segments[1], contactName: requiredString(body, "contactName", 200), contactEmail: requiredString(body, "contactEmail", 254), contactPhone: optionalString(body, "contactPhone", 50) }); return dataResponse({ id: profile.props.id.value, customerId: profile.props.customerId.value, contactName: profile.props.contactName, contactEmail: profile.props.contactEmail.value, contactPhone: profile.props.contactPhone, updatedAt: profile.props.updatedAt }, 200); }
  if (segments[0] === "customers" && segments[2] === "billing-notes") { const note = await new AddBillingNoteService(new D1BillingRepository(runtime.db), new D1SubscriptionRepository(runtime.db), pricingRepository, runtime.ids, runtime.clock, audit).execute({ customerId: segments[1], subscriptionId: optionalString(body, "subscriptionId", 80), invoiceId: optionalString(body, "invoiceId", 80), body: requiredString(body, "body", 4_000), authorAdminUserId: principal.adminUserId }); return dataResponse({ id: note.props.id.value, customerId: note.props.customerId.value, subscriptionId: note.props.subscriptionId?.value ?? null, invoiceId: note.props.invoiceId?.value ?? null, body: note.props.body, createdAt: note.props.createdAt }, 201); }
  if (segments[0] === "subscriptions" && segments.length === 3 && segments[2] === "operations") { const lifecycle = new SubscriptionLifecycleService(new D1SubscriptionRepository(runtime.db), runtime.ids, runtime.clock, audit); const subscription = await executeSubscriptionOperation(lifecycle, segments[1], body); return dataResponse(subscriptionDto(subscription), 200); }
  if (segments[0] === "subscriptions") { const subscription = await new CreateSubscriptionService(new D1SubscriptionRepository(runtime.db), pricingRepository, new D1CatalogueRepository(runtime.db), pricing, runtime.ids, runtime.clock, audit).execute({ customerId: requiredString(body, "customerId", 80), planId: requiredString(body, "planId", 80), billingInterval: requiredString(body, "billingInterval", 20) as BillingInterval, initialStatus: (optionalString(body, "initialStatus", 20) ?? "PENDING") as "PENDING" | "TRIAL" | "ACTIVE", trialEndsAt: optionalDate(body, "trialEndsAt"), currentPeriodStart: optionalDate(body, "currentPeriodStart"), currentPeriodEnd: optionalDate(body, "currentPeriodEnd") }); return dataResponse(subscriptionDto(subscription), 201); }
  if (segments[0] === "service-credentials" && segments.length === 1) { const issued = await new ManageServiceCredentialService(runtime.security, new AdminAuthorizationGuard(), runtime.ids, runtime.clock, audit).issue(principal, { name: requiredString(body, "name", 160), scopes: parseServiceScopes(body.scopes), expiresAt: requiredDate(body, "expiresAt") }); return dataResponse({ credential: credentialDto(issued.credential), token: issued.rawToken }, 201); }
  if (segments[0] === "service-credentials" && segments[2] === "rotate") { const issued = await new ManageServiceCredentialService(runtime.security, new AdminAuthorizationGuard(), runtime.ids, runtime.clock, audit).rotate(principal, segments[1], requiredDate(body, "expiresAt")); return dataResponse({ credential: credentialDto(issued.credential), token: issued.rawToken }, 201); }
  throw routeNotFound();
}

function readPermission(segments: string[]): PermissionCode { if (segments[0] === "customers") return segments[2] === "pricing" ? "PRICE_READ" : segments[2] === "billing" ? "BILLING_READ" : "CUSTOMER_READ"; if (["plans", "offerings"].includes(segments[0])) return "CATALOG_READ"; if (segments[0] === "prices") return "PRICE_READ"; if (["discounts", "promotion-codes"].includes(segments[0])) return "DISCOUNT_READ"; if (segments[0] === "subscriptions") return "SUBSCRIPTION_READ"; if (segments[0] === "audit-events") return "AUDIT_READ"; throw routeNotFound(); }
function writePermission(segments: string[]): PermissionCode { if (segments[0] === "customers" && segments.length === 1) return "CUSTOMER_WRITE"; if (segments[0] === "customers" && segments[2] === "price-overrides") return "PRICE_WRITE"; if (segments[0] === "customers" && segments[2] === "pricing") return "PRICE_READ"; if (segments[0] === "customers" && ["billing-profile", "billing-notes"].includes(segments[2])) return "BILLING_WRITE"; if (segments[0] === "customers" && segments[2] === "discounts") return "DISCOUNT_WRITE"; if (["plans", "offerings"].includes(segments[0])) return "CATALOG_WRITE"; if (segments[0] === "prices") return "PRICE_WRITE"; if (["discounts", "promotion-codes"].includes(segments[0])) return "DISCOUNT_WRITE"; if (segments[0] === "subscriptions") return "SUBSCRIPTION_WRITE"; if (segments[0] === "service-credentials") return "ADMIN_USER_MANAGE"; throw routeNotFound(); }
function found(value: unknown, code: string) { if (!value) throw new DomainConflictError(code, "Requested resource does not exist."); return dataResponse(value); }
function routeNotFound(): DomainConflictError { return new DomainConflictError("API_ROUTE_NOT_FOUND", "API route does not exist."); }
function customerDto(value: Awaited<ReturnType<CreateCustomerService["execute"]>>) { const p = value.snapshot; return { id: p.id.value, externalReference: p.externalReference, businessName: p.businessName, contactName: p.contactName, email: p.email.value, phone: p.phone, industry: p.industry, websiteUrl: p.websiteUrl, status: p.status, creationSource: p.creationSource, createdAt: p.createdAt }; }
function planDto(value: Awaited<ReturnType<CatalogueManagementService["createPlan"]>>) { const p = value.props; return { id: p.id.value, code: p.code.value, name: p.name, description: p.description, active: p.active, featured: p.featured, custom: p.custom, displayOrder: p.displayOrder, createdAt: p.createdAt }; }
function offeringDto(value: Awaited<ReturnType<CatalogueManagementService["createOffering"]>>) { const p = value.props; return { id: p.id.value, code: p.code.value, name: p.name, description: p.description, category: p.category, active: p.active, displayOrder: p.displayOrder, createdAt: p.createdAt }; }
function priceDto(value: Awaited<ReturnType<PublishPlanPriceService["execute"]>>) { const p = value.props; return { id: p.id.value, planId: p.planId.value, billingInterval: p.billingInterval, amountMinor: p.amount.amountMinor, setupFeeMinor: p.setupFee.amountMinor, currency: p.amount.currency, taxBehaviour: p.taxBehaviour, effectiveFrom: p.effectiveRange.effectiveFrom, effectiveTo: p.effectiveRange.effectiveTo }; }
function overrideDto(value: Awaited<ReturnType<CreatePriceOverrideService["execute"]>>) { const p = value.props; return { id: p.id.value, customerId: p.customerId.value, planId: p.planId.value, billingInterval: p.billingInterval, amountMinor: p.amount.amountMinor, setupFeeMinor: p.setupFee.amountMinor, currency: p.amount.currency, status: p.status, effectiveFrom: p.effectiveRange.effectiveFrom, effectiveTo: p.effectiveRange.effectiveTo, reason: p.reason }; }
function discountDto(value: Awaited<ReturnType<CreateDiscountService["execute"]>>) { const p = value.props; return { id: p.id.value, code: p.code.value, name: p.name, discountType: p.discountType, percentOffBasisPoints: p.percentOffBasisPoints, amountOffMinor: p.amountOff?.amountMinor ?? null, currency: p.amountOff?.currency ?? null, durationType: p.durationType, durationMonths: p.durationMonths, active: p.active, stackable: p.stackable, startsAt: p.effectiveRange.effectiveFrom, endsAt: p.effectiveRange.effectiveTo }; }
function promotionDto(value: Awaited<ReturnType<CreatePromotionCodeService["execute"]>>) { const p = value.props; return { id: p.id.value, discountId: p.discountId.value, code: p.code.value, customerId: p.customerId?.value ?? null, planId: p.planId?.value ?? null, active: p.active, startsAt: p.effectiveRange.effectiveFrom, expiresAt: p.effectiveRange.effectiveTo, maxRedemptions: p.maxRedemptions, firstPurchaseOnly: p.firstPurchaseOnly }; }
function customerDiscountDto(value: Awaited<ReturnType<ApplyCustomerDiscountService["execute"]>>) { const p = value.props; return { id: p.id.value, customerId: p.customerId.value, discountId: p.discountId.value, subscriptionId: p.subscriptionId?.value ?? null, source: p.source, status: p.status, effectiveFrom: p.effectiveRange.effectiveFrom, effectiveTo: p.effectiveRange.effectiveTo, reason: p.reason }; }
function subscriptionDto(value: Awaited<ReturnType<CreateSubscriptionService["execute"]>>) { const p = value.props; return { id: p.id.value, customerId: p.customerId.value, planId: p.planId.value, status: p.status, billingInterval: p.billingInterval, currency: p.currency, startedAt: p.startedAt, currentPeriodStart: p.currentPeriodStart, currentPeriodEnd: p.currentPeriodEnd, gracePeriodEndsAt: p.gracePeriodEndsAt, serviceExtendedUntil: p.serviceExtendedUntil, cancelAt: p.cancelAt, cancelledAt: p.cancelledAt, trialEndsAt: p.trialEndsAt, version: p.version, createdAt: p.createdAt, updatedAt: p.updatedAt }; }
function credentialDto(value: Awaited<ReturnType<ManageServiceCredentialService["issue"]>>["credential"]) { const p = value.props; return { id: p.id.value, name: p.name, scopes: p.scopes, status: p.status, expiresAt: p.expiresAt, rotatedFromId: p.rotatedFromId?.value ?? null, createdAt: p.createdAt }; }

async function executeSubscriptionOperation(lifecycle: SubscriptionLifecycleService, id: string, body: Record<string, unknown>) {
  switch (requiredString(body, "operation", 40)) {
    case "MARK_PAST_DUE": return lifecycle.markPastDue(id, requiredDate(body, "gracePeriodEndsAt"));
    case "SUSPEND": return lifecycle.suspend(id);
    case "RESUME": return lifecycle.resume(id);
    case "SCHEDULE_CANCELLATION": return lifecycle.scheduleCancellation(id);
    case "CANCEL_IMMEDIATELY": return lifecycle.cancel(id);
    case "FINALIZE_CANCELLATION": return lifecycle.finalizeCancellation(id);
    case "EXTEND_SERVICE": return lifecycle.extendService(id, requiredDate(body, "serviceExtendedUntil"), requiredString(body, "reason", 500));
    default: throw new DomainConflictError("INVALID_SUBSCRIPTION_OPERATION", "Subscription operation is invalid.");
  }
}

function billingOverviewDto(value: Awaited<ReturnType<CustomerBillingOverviewService["execute"]>>) {
  const subscription = value.subscription;
  return {
    profile: value.profile ? { id: value.profile.id.value, customerId: value.profile.customerId.value, contactName: value.profile.contactName, contactEmail: value.profile.contactEmail.value, contactPhone: value.profile.contactPhone, updatedAt: value.profile.updatedAt } : null,
    subscription: subscription ? { ...subscription, id: subscription.id.value, customerId: subscription.customerId.value, planId: subscription.planId.value } : null,
    pricing: value.pricing,
    paymentState: value.paymentState,
    entitlementState: value.entitlementState,
    invoices: value.invoices.map((invoice) => ({ ...invoice, id: invoice.id.value, customerId: invoice.customerId.value, subscriptionId: invoice.subscriptionId?.value ?? null, billingAccountId: invoice.billingAccountId?.value ?? null, subtotalMinor: invoice.subtotal.amountMinor, taxMinor: invoice.tax.amountMinor, totalMinor: invoice.total.amountMinor, amountDueMinor: invoice.amountDue.amountMinor, lines: undefined })),
    notes: value.notes.map((note) => ({ ...note, id: note.id.value, customerId: note.customerId.value, subscriptionId: note.subscriptionId?.value ?? null, invoiceId: note.invoiceId?.value ?? null, authorAdminUserId: note.authorAdminUserId.value })),
  };
}
