import { AiDemo, FAQList } from "@/components/Interactive";
import { CtaBand, IndustryCard, PricingSection, SectionHeading, ServiceCard } from "@/components/Sections";
import { StructuredData } from "@/components/SiteChrome";
import { brand, faqs, industries, services } from "@/lib/config";
import { organisationSchema } from "@/lib/seo";

const steps = [
  ["01", "Get Found", "Show up with a fast website, strong local search foundations and a cared-for Google profile.", "/local-seo"],
  ["02", "Build Trust", "Give prospects consistent information, genuine feedback and an active professional presence.", "/reputation-management"],
  ["03", "Respond Instantly", "Answer common questions and capture structured enquiries—even after hours.", "/ai-receptionist"],
  ["04", "Book More Work", "Qualify the need, offer an available time and hand over the complete lead.", "/whatsapp-booking"],
];

export default function Home() {
  return <>
    <StructuredData data={organisationSchema()} />
    <section className="hero dark-section"><div className="magnet-orbit orbit-one" /><div className="magnet-orbit orbit-two" /><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow light">The Digital Growth System for Local Business</span><h1>Get found.<br />Build trust.<br /><em>Book more work.</em></h1><p>{brand.name} builds and manages everything your local business needs to grow online—from a high-converting website and stronger Google presence to reputation management and a 24/7 AI receptionist that answers, qualifies and books.</p><div className="cta-group"><a className="button" href={brand.cta.primary.href}>{brand.cta.primary.label}<span aria-hidden="true">↗</span></a><a className="text-button" href={brand.cta.secondary.href}>{brand.cta.secondary.label}<span aria-hidden="true">→</span></a></div><div className="trust-row"><span className="avatar-stack" aria-hidden="true"><i>AU</i><i>24</i><i>7</i></span><span><strong>Built for Australian local businesses</strong><small>Trades · Home services · Professional services</small></span></div></div><div className="hero-product" aria-label="Product flow preview"><div className="search-preview"><small>Local search</small><strong>Emergency plumber near me</strong><span>{brand.name} customer · Open now</span></div><div className="flow-line"><span>Found</span><i /><span>Answered</span><i /><span>Booked</span></div><div className="conversation-preview"><div className="preview-head"><span className="status-dot" /> AI receptionist <small>Online</small></div><p className="mini-bubble">Our hot water stopped. Can someone come today?</p><p className="mini-bubble reply">I can help. What suburb are you in?</p><div className="lead-strip"><span>Qualified lead</span><strong>Today · 2:30 pm</strong><small>Google Calendar</small></div></div><div className="booked-stamp"><span>✓</span><strong>Appointment booked</strong><small>Lead sent to business</small></div></div></div></section>

    <section className="problem-section section"><div className="container split"><SectionHeading eyebrow="The hidden cost of disconnected marketing" title="Every gap is a chance for a good enquiry to disappear." copy="Local growth rarely fails because of one big problem. It leaks through a collection of small, disconnected moments." /><div className="problem-list">{["A website that looks fine but does not guide action", "A Google profile that slowly becomes outdated", "Reviews requested inconsistently—or never answered", "Social profiles that fall silent", "After-hours enquiries waiting until morning", "Booking that turns into message ping-pong"].map((item, index) => <div key={item}><span>0{index + 1}</span><p>{item}</p></div>)}</div></div></section>

    <section className="system-section section"><div className="container"><SectionHeading eyebrow="One connected growth system" title="From local search to confirmed booking." copy="Each part strengthens the next, so attention becomes trust, trust becomes conversation, and conversation becomes a clear next step." align="center" /><div className="system-steps">{steps.map(([number, title, copy, href]) => <a href={href} key={title}><span>{number}</span><div className="step-icon" aria-hidden="true">✦</div><h3>{title}</h3><p>{copy}</p><i aria-hidden="true">→</i></a>)}</div></div></section>

    <section id="demo" className="demo-section section dark-section"><div className="container"><div className="demo-heading"><SectionHeading eyebrow="A receptionist that captures the full picture" title="One message in. A structured lead out." copy="Try a deterministic example built from local demo data. It never sends, stores or processes real personal information." /><span className="demo-badge"><i /> Interactive demonstration</span></div><AiDemo /><p className="disclaimer">Demonstration only. Available features depend on your selected package, approved knowledge and integrations.</p></div></section>

    <section id="services" className="section services-section"><div className="container"><div className="heading-row"><SectionHeading eyebrow="Everything needed to grow locally" title="Six capabilities. One accountable system." copy="Strategy, build, connection and ongoing improvement—managed as one coherent customer journey." /><a className="text-link" href="/pricing">Explore packages →</a></div><div className="service-grid">{services.map(service => <ServiceCard key={service.href} service={service} />)}</div></div></section>

    <section className="ethics-section section"><div className="container ethics-grid"><div className="ethics-visual"><div className="review-card r1"><span>★★★★★</span><strong>Genuine feedback</strong><small>Verified customer experience</small></div><div className="review-card r2"><span>Response drafted</span><strong>Professional and useful</strong><small>Ready for business approval</small></div><div className="ethics-seal"><span>✓</span> Ethical by design</div></div><div><SectionHeading eyebrow="Reputation without shortcuts" title="Trust is earned. Your review system should reflect that." copy="We help you ask consistently, respond professionally and learn from genuine customer feedback." /><ul className="check-list"><li>Genuine customer feedback only</li><li>No incentives for positive reviews</li><li>No selective review gating</li><li>No fabricated or manipulated reviews</li></ul><a className="button secondary" href="/reputation-management">Our ethical approach</a></div></div></section>

    <section className="section pricing-preview"><div className="container"><SectionHeading eyebrow="Clear packages for different stages" title="Start with the growth system that fits now." copy="Every package is managed, measurable and designed to build on a strong foundation." align="center" /><PricingSection /><p className="pricing-note">All prices are in Australian dollars and exclude GST. Scope and third-party costs are confirmed before work begins. <a href="/pricing">See full pricing and disclosures.</a></p></div></section>

    <section className="section industries-section"><div className="container"><div className="heading-row"><SectionHeading eyebrow="Built around real local buying journeys" title="Different industries. The same missed-opportunity problem." copy="We shape the system around how customers search, compare, enquire and book in your category." /><a className="text-link" href="/industries">View all industries →</a></div><div className="industry-grid">{industries.slice(0, 4).map(industry => <IndustryCard key={industry.href} industry={industry} />)}</div></div></section>

    <section className="process section dark-section"><div className="container"><SectionHeading eyebrow="A practical path to launch" title="No mystery. No handballing." align="center" /><div className="process-row">{["Audit", "Build", "Connect", "Launch", "Improve"].map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong>{index < 4 && <i aria-hidden="true" />}</div>)}</div></div></section>

    <section className="section faq-section"><div className="container split faq-split"><SectionHeading eyebrow="Questions worth asking" title="Clear answers before you commit." copy="If your question is not here, ask us directly. Good fit starts with a candid conversation." /><FAQList items={faqs} /></div></section>
    <CtaBand />
  </>;
}
